roboflow/supervision

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature-request.yml, .github/ISSUE_TEMPLATE/question.yml, .github/workflows/test.yml
- 🐞 Bug Report, 🤩 Feature Request and ❓ Question issue templates added
=> 🐞 Bug Report, 🤩 Feature Request and ❓ Question issue templates

CITATION.cff, CONTRIBUTING.md
This PR adds a `CITATION.cff` file to the repository to inform library users how to cite `supervision` in their work.
-   [X] Documentation change
N/A
N/A
N/A
=> Create CITATION.cff file

supervision/__init__.py
Add export of linezone
This adds LineZone and LineZoneAnnotator to the manin __init__ file so they can be easily referenced.
To close Issue #30
YOUR_ANSWER
=> Update __init__.py to include linezone

supervision/detection/line_counter.py
Added `_` for the LineZone trigger function to properly unpack values. 
I created a [Detections](https://github.com/roboflow/supervision/blob/e091f9c9594bcb1d04a8fbfffc885722c4c2c765/supervision/detection/core.py#L51) class using yolov8 results, and passed those detections into a LineZone.trigger() call and no longer receive the error `too many values to unpack (expected 4)`
=> Fix issue where the LineZone.trigger function expects 4 values instead of 5

supervision/detection/core.py
Change the class variable ordering in Detections to match the `__iter__` function
#69 
N/A
N/A
Variable ordering now in line with `__iter__` function
=> Make Detection docs consistent with __iter__

supervision/detection/core.py, test/detection/test_core.py
- ➕ Add `Detections.merge` method
- 🧪 Add unit tests for `Detections.merge` method
- 📚 Add documentation tests for `Detections.merge` method
This PR is related to https://github.com/roboflow/supervision/issues/80.
=> ➕ Add `Detections.merge` method

supervision/dataset/core.py, supervision/dataset/formats/pascal_voc.py, supervision/dataset/formats/yolo.py, supervision/dataset/ultils.py, supervision/file.py, test/dataset/formats/test_yolo.py
YOLO Dataset loader is designed to be as flexible as possible to allow data consistency for both mixed and non-mixed datasets. You can test API in [this example notebook](https://colab.research.google.com/drive/1yyIFExkgks24JGX2jOf8TLAYTSIFIUhy?usp=sharing).
- box dataset
- mask dataset
- non-mixed datasets
- To load a consistent YOLO dataset. Only boxes or boxes and polygons. 
```python
dataset = sv.Dataset.from_yolo(
images_directory_path=f"{dataset.location}/train/images",
annotations_directory_path=f"{dataset.location}/train/labels",
data_yaml_path=f"{dataset.location}/data.yaml",
force_masks=False
)
```
- Force consistent mask loading from mixed-label YOLO dataset.
```python
dataset = sv.Dataset.from_yolo(
images_directory_path=f"{dataset.location}/train/images", …
```
=> support for yolo dataset loading and saving

supervision/detection/line_counter.py
This PR adds 2 new parameters for the  class `LineZoneAnnotator` in order to add a custom label instead of only using in/out labels. This idea occurred to us on a project where we needed to show the real time obj detection with a context of what in & out means for example: in means numbers of runs completed for a machine.
=> Add custom text for the in & out tags

README.md
Example in README documentation out of date for v.0.8.0.  __iter__() yields a length 3 tuple.  Example shows a length 2 tuple. 
Change proposed: add image_name to example to align with current version of DetectorDataset objects.
Reference: From API docs
```
__iter__() ¶
Iterate over the images and annotations in the dataset.
Yields:
Type	Description
Iterator[Tuple[str, np.ndarray, Detections]]	
Iterator[Tuple[str, np.ndarray, Detections]]: An iterator that yields tuples containing the image name, the image data, and its corresponding annotation.
```
[X] Documentation …
=> Update README.md example for looping through dataset

supervision/detection/core.py
Current `Detection` class only support for yolov8 object detection. Segmentation masks information are missing.
```
model = YOLO(model="yolov8s.pt")
results = model.predict(img)[0]
detections = sv.Detections.from_yolov8(results)
mask_annotator = sv.MaskAnnotator()
box_annotator = sv.BoxAnnotator()
img = box_annotator.annotate(scene=img, detections=detections)
img = mask_annotator.annotate(scene=img, detections=detections)
```
=> Adding yolov8 masks to detections

supervision/detection/tools/polygon_zone.py
Now you can pass polygon zone vertices as int and float values. This fixes the problem reported in #106.
=> 🛠️ Fix #106 - now you can pass polygon with int and float vertices.

supervision/dataset/core.py, supervision/dataset/formats/coco.py, supervision/detection/core.py, supervision/utils/file.py, test/dataset/formats/test_coco.py
- Added a support for `COCO` detection dataset import and export
- Added a support for reading and writing `json` files
- Related issue #141 
- Tested locally with dataset coco128 (downloaded from roboflow)
- Import using `supervision.DetectionDataset`
- Visualized using `supervision.BoxAnnotator`
- Saved dataset using `supervision.DetectionDataset`
-   [x] Docs updated?
=> COCO Detection Dataset Import/Export support

supervision/dataset/core.py, supervision/dataset/formats/coco.py, supervision/dataset/utils.py, test/dataset/formats/test_coco.py, test/dataset/test_core.py, test/dataset/test_utils.py, test/detection/test_core.py, test/utils.py
Related issue: #155
- Documentaion needs to change
- Check docstrings
=> Dataset merge

supervision/dataset/core.py
This PR fixes a bug where, if the `classification.get_top_k(1)[0][0]` line of code is called in the `as_folder_structure` function, an error is returned.
=> Fix top_k processing in as_folder_structure

supervision/dataset/formats/coco.py, test/dataset/formats/test_coco.py
Draft of PR fixing issues mentioned https://github.com/roboflow/supervision/pull/150. It is an alternative to the https://github.com/roboflow/supervision/pull/169 solution.
=> 🛠️ fix incorrect COCO class id loading

setup.py, supervision/detection/annotate.py
This PR solves the issue in rendering unicode label. For more details, please see issue #143
The unicode rendering issue is not caused by `Supervision` itself. Thus, I think this is a new feature. 
No breaking change added.
For not violating the framework layout, I leave the primitive code in the source with comment. I think it's better be an absolute layer of text rendering (maybe?)
I tested the code with my project in Chinese. It works fine.
With unicode label support, some fancy features can be achieved. Like drawing emoji in labels, or auto label translation with translation api.
=> Add unicode label support

supervision/__init__.py
Fix #213 for no install method (poetry or pip install .  "install package" so we can find version If none happen __version__ check will fail, to prevent that changed in to "development" tag for set to version.
=> fix: 🐛 package version control if PackageNotFoundError occured

supervision/dataset/formats/yolo.py, supervision/metrics/detection.py
It is the fix for #212. Turns out that the problem is not with the confusion matrix but with the loading of the YOLO dataset. I thought that `names` value in `data.yaml` can only be `List[str]` but it can also be `Dict[int, str]`. I added some logic to handle that.
- Tested in Google Colab
=> 🛠️ #212 bug fix

supervision/dataset/formats/coco.py
Fixes https://github.com/roboflow/supervision/issues/205
The issue was compatible with supervision because even though supervision exports data in the wrong format, its function to read coco dataset works for both the correct and malformed output format 
Refer: https://github.com/roboflow/supervision/blob/20954a299660a1f227a772a0a7cd253761ddb9da/supervision/dataset/formats/coco.py#L87
```
polygons = [
np.reshape(
np.asarray(image_annotation["segmentation"], dtype=np.int32), (-1, 2)
)
for image_annotation in image_annotations
]
```
Regardless of the format of `image_annotation["segmentation"]`, data is loaded in expected shape 
With this fix, data stored will be in expected format. 
- …
=> Format coco output data as per standard

supervision/detection/core.py
Fix mask array shape in docstrings (n, W, H) -> (n, H, W)
More details in #254
-   [X] Doc fix (non-breaking change which fixes an issue)
No need; is a change in documentation
-   [X] Docs updated? What were the changes: All array shapes (n, W, H) change to (n, H, W)
=> Update core.py (n, W, H) -> (n, H, W)

docs/metrics/detection.md, supervision/__init__.py, supervision/dataset/core.py, supervision/metrics/detection.py, test/metrics/test_detection.py, test/utils.py
This pr is related to feature #206 and #232.
Google colab for testing:https://colab.research.google.com/drive/1MT5wc6H8WPshQfPoQITr6mLOcfd47x5E?usp=sharing
-   [x] Docs updated at `docs/supervision/metrics/detection`
- Ultralytics
- Torchmetrics (utilizes CocoApi)
=> Feature MeanAveragePrecision 🔥 

supervision/detection/core.py
`sv.Detections.from_ultralytics() ` and `sv.Classifications.from_ultralytics()`  have different outputs I think it is a overlook part in documentation in https://github.com/roboflow/supervision/pull/281. If I missing something please let me know. 
Thank you.
=> fix(docs): 📚🐛 deprecated for "from_yolov8" desc fix for detection

supervision/detection/utils.py, test/detection/test_utils.py
Fixes issue - https://github.com/roboflow/supervision/issues/299
Test script provided under the issue
=> Fix issue #299

README.md
Fix SAM video URL on README, in the "tutorials" section.
-  [x] This change requires a documentation update
=> Fix SAM video URL on README

.github/workflows/publish.yml
I added tag release and remove install deps because we don't need it. Twine can handle without it.
=> ci(pypi): 🚧 release pypi action automatic release per tag and main branch

supervision/detection/core.py
This PR is for #347 . The main reason was that it was not able to handle empty detections. Also documentation is fixed now.
Colab link: https://colab.research.google.com/drive/17AROUpY_vHKXW0RG2_4VzXiDqPps09TI?usp=sharing
=> fixed empty detections for deepsparse

supervision/detection/core.py
We have multiple different detection and in case of video or multiple images it can be return empty so prevent that workflow break we should check all other detection type xyxy in case of empty boxes and continue 
=> fix: 🐛 Empty check for xyxy results for prevent ValueError and return as empty detection

docs/detection/annotate.md, supervision/__init__.py, supervision/annotators/core.py
We have box annotator and for support different shape I added circle annotator
```python
from ultralytics import YOLO
import cv2
circle_annotator = sv.CircleAnnotator()
model = YOLO("yolov8n.pt") 
results = model("bus.jpg")
detections = sv.Detections.from_ultralytics(results[0])
frame = cv2.imread("bus.jpg")
annotated_frame = circle_annotator.annotate(
scene=frame.copy(), 
detections=detections, 
)
cv2.imshow("frame", annotated_frame)
cv2.waitKey(0)
```
=> feat(annotator): 🚀 introduce circle annotator

CODE_OF_CONDUCT.md
This PR adds the Roboflow community reports email to our Code of Conduct.
=> Add email to Code of Conduct

supervision/detection/core.py, supervision/detection/utils.py, test/detection/test_utils.py
remoed class_list arg from core.py file
No need to ask user for providing  `class_list`
simplify the [sv.Detections.from_roboflow](https://supervision.roboflow.com/detection/core/#supervision.detection.core.Detections.from_roboflow) API and remove extra argument.
solved this issue : https://github.com/roboflow/supervision/issues/394
-   [ x] New feature (non-breaking change which adds functionality)
-   [ x] This change requires a documentation update
- once this is perfect ill update docs
=> Remove class list dependency for roboflow to detection conversion

supervision/detection/tools/inference_slicer.py
This PR adds concurrent processing with the `concurrent.futures` threading method (part of the [Python standard library](https://docs.python.org/3/library/concurrent.futures.html)) to `sv.InferenceSlicer` processing.
This PR drastically reduces inference times with the slicer.
Without concurrent processing:
```
Detections w/o SAHI: 127
--- 1.460580825805664 seconds ---
Detections w/ SAHI: 146
--- 13.294042110443115 seconds ---
``` 
With concurrent processing slicer:
```
Detections w/o SAHI: 127
--- 1.4807708263397217 seconds ---
Detections w/ SAHI: 146
--- 2.305016040802002 seconds ---
```
-   [ ] This change requires a …
=> Add concurrent processing for `sv.InferenceSlicer`

supervision/annotators/core.py
Added a new argument, 'color_map' in InferenceSlicer to provide more options for color coding while annotating. This includes mapping colors by 'index', 'class' or 'track'. Also refactored the way colors are resolved by separating the responsibility into a new function 'resolve_color_idx' and 'resolve_color'.
=> Add color mapping strategy to InferenceSlicer

supervision/draw/color.py
Added #a351fb as the first default color in `sv.draw.color.ColorPalette`
Fix: #424 
-   [x] Enhancement/ Bug fix (non-breaking change which fixes an issue)
=> add #a351fb as first default color into sv.draw.color.ColorPalette

supervision/annotators/core.py
This PR is related to https://github.com/roboflow/supervision/issues/417
I've made some enhancements to sv.MaskAnnotator.
1. calc bgr color once for color mask creation
2. replace np.where with cv2.add operation for scene with hole and colored object
speed up two times
=> faster sv.MaskAnnotator

supervision/tracker/byte_tracker/core.py
Fixes #429. When `sv.Detections` is empty (`len(detections) == 0`) `sv.ByteTrack` returns `np.array([], dtype=int)`
=> Fix return value when sv.Detections is empty

supervision/tracker/byte_tracker/core.py
**Description:**
This pull request addresses the following changes:
1. **ByteTrack Enhancement:**
- Modified the `ByteTrack` module to retain information about the mask  #418 .
2. **Base Code Modification:**
- Made adjustments to the base code to resolve the issue.
**Changes Made:**
- Added the attribute "mask" to the `STrack` class, initialized to `None` by default.
- Modified the `update` and `reactivate` methods of the `STrack` class to update the `mask` attribute with the new detection.
**Testing:**
Successfully tested the code with both object-detection and segmentation-models using the provided testing code:
```python
from tqdm import tqdm
from ultralytics import YOLO
model = YOLO('yolov8x.pt')
video_info = …
```
=> #418 Make sv.ByteTrack work with segmentation model 

supervision/detection/core.py, supervision/detection/utils.py, test/detection/test_utils.py
Resolving #434 
Extended `sv.Detections.from_roboflow` and `process_from_roboflow` to use `tracker_id` when provided
Extended test cases to support different types of scenarios when `tracker_id` is and is not provided.
=> Update sv.Detections.from_roboflow to extract tracker_id values from inference response

docs/index.md
pip editable install for toml file require recent version pip so for python3.8 old pip version I added update to make sure user/developer has recent version and able to install editable install properly without error.  Fix: #467
=> docs: 📓 development virtualenv installation pip upgrade added

supervision/__init__.py, supervision/annotators/core.py, supervision/annotators/utils.py, test/annotators/test_utils.py
Adjusted the way colors are applied to detection annotations to support custom color schemes. Modified 'ColorMap' to 'ColorLookup' across multiple files, adding the ability to use a color lookup array. This refinement will enable users to assign custom colors to different detection annotations, offering greater flexibility in the visual representation of detection data. Updated related tests to reflect these changes.
=> Update color mapping system in detection annotations

custom_theme/404.html, mkdocs.yml
This PR adds a 404 page to `supervision`.
Here is the current page someone sees when they navigate to a broken URL:
Here is the page this PR adds:
=> Add 404 page

mkdocs.yml
This PR adds a `/` to the end of our mkdocs site URL, required for custom pages to resolve paths correctly.
=> Add `/` to mkdocs site_url

mkdocs.yml
This PR should fix the continued issues with 404 pages. `mkdocs` is particular when it comes to URL paths.
The 404 page right now is trying to request:
```
https://supervision.roboflow.com/supervision/assets/_mkdocstrings.css
```
The `/supervision` part is taken from our `mkdocs` config and is now redundant since we deploy on `supervision.roboflow.com`.
=> Change domain to supervision.roboflow.com in mkdocs

supervision/detection/line_counter.py
As requested in the issue #464 , I have made the necessary changes. Now the [sv.LineZone.trigger](https://github.com/roboflow/supervision/blob/5b5e0eb88daec92643834b2284e750ad5a1c7dc6/supervision/detection/line_counter.py#L30) returns a bool nparray which indicates the object's state change (indicating it has crossed the line). The implementation is similar to that of [sv.PolygonZone.trigger](https://github.com/roboflow/supervision/blob/5b5e0eb88daec92643834b2284e750ad5a1c7dc6/supervision/detection/tools/polygon_zone.py#L45)
=> Linezone.trigger returns bool nparray

docs/annotators.md, supervision/__init__.py, supervision/annotators/core.py
A HeatMapAnnotator class has been added for visualization purposes. This class can be used to draw heatmaps on an image based on provided detections, where the heat accumulates over time and is drawn as a semi-transparent overlay of blurred circles.
=> Add HeatMapAnnotator class to supervision

supervision/draw/utils.py
Implementation of https://github.com/roboflow/supervision/issues/439, that adds the possibility to add a watermark image to the specified scene.
Both transparent and opaque watermarks have been tested.
=>  feat: 🚀 Enable Watermarking images and videos

custom_theme/404.html, docs/changelog.md, mkdocs.yml, pyproject.toml
The custom 404.html was removed as it was no longer necessary with the updates to the Mkdocs.yml file. Upgraded the project version from `0.16.0rc2` to `0.16.0rc3` in the `pyproject.toml` file. Various updates were added to the changelog.md to reflect improvements and bug fixes in the new project release. This includes new annotations, utility improvements, and bug-fixes to improve project functionality.
=> Remove custom 404 page and update documentation for new release

docs/assets.md, pyproject.toml, supervision/assets/__init__.py, supervision/assets/downloader.py, supervision/assets/list.py
Fix: `from supervision.assets import download_assets`
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-3-989c1cade8ed>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from supervision.assets import download_assets
1 frames
[/usr/local/lib/python3.10/dist-packages/supervision/assets/downloader.py](https://localhost:8080/#) in <module>
5 from typing import Union
6 
----> 7 from supervision.assets import VideoAssets
8 from supervision.assets.list import VIDEO_ASSETS
9 
ImportError: cannot import name 'VideoAssets' from partially initialized module 'supervision.assets' (most likely due to a circular import) …
```
=> Assets fix

supervision/annotators/core.py, supervision/detection/tools/polygon_zone.py, supervision/detection/utils.py, test/detection/test_utils.py
The coordinates of the detections object were found to have negative values in some cases, probably due to the trajectory prediction obtained with ByteTrack. Because of these negative coordinates, the ROI object was becoming null, which caused problems when calling cv2.blur(), as a valid array was expected.
The solution implemented for this bug was adjustment the command:
`detections.xyxy[detection_idx].astype(int)`
To:
`np.maximum(detections.xyxy[detection_idx].astype(int), 0)`
This way, whenever there is a negative coordinate, it will be mapped to 0.
[Google Colab Notebook: Example of the error occurring](https://colab.research.google.com/drive/1g-hOAe3jsgY_24yNszWblWWjV9lPkLxv?usp=sharing)
[Google Colab Notebook: Test with …
=> fix: #540 bug blur annotator

docs/annotators.md, supervision/__init__.py, supervision/annotators/core.py
It implemented the PolygonAnnotator class in the core.py file under the supervision/annotators directory to support drawing polygons over detected objects. This was done by dividing the masks into multiple polygons and drawing them on the image.
=> Add PolygonAnnotator and update documentation

supervision/__init__.py, supervision/annotators/core.py, supervision/annotators/utils.py, supervision/detection/core.py, supervision/detection/tools/polygon_zone.py, supervision/detection/utils.py, supervision/geometry/core.py, test/detection/test_core.py, test/detection/test_utils.py
Added `calculate_centroids` function to compute center of mass for binary mask representations. Method added to `utils.py` and method import added to `core.py`. `Position` enumeration updated with `CENTER_OF_MASS` constant. Test function is added with test cases covering different mask scenarios. Update allows for masks to carry center of mass information too, useful in object detection.
=> Add centroid calculation for binary masks

supervision/annotators/core.py
* Combined all colored masks before applying them to the scene
* Made sure that returned ndarray is np.uint8 for video writer simplicity
https://github.com/roboflow/supervision/issues/472
I profiled the code with VizTracer and compared outputs frame by frame and they are equal.
=> Feature/make sv.mask annotator as fast as annotators in popular detection frameworks #472

supervision/classification/core.py
This PR adds a data loader for classifications from the `timm` Python package.
You can test the API using the following code:
```python
import timm
import torch
from PIL import Image
from timm.data import resolve_data_config
from timm.data.transforms_factory import create_transform
model = timm.create_model(
'hf-hub:nateraw/resnet50-oxford-iiit-pet',
pretrained=True
)
model.eval()
transform = create_transform(**resolve_data_config(model.pretrained_cfg, model=model))
labels = model.pretrained_cfg['label_names']
top_k = min(len(labels), 5)
image = Image.open('./annotated_image.jpg').convert('RGB')
x = transform(image).unsqueeze(0)
out = model(x)
results = sv.Classifications.from_timm(out) …
```
=> Add timm data loader for `sv.Classifications`

.github/workflows/docs.yml
This PR adds the `mkdocs-material[imaging]` dependency to the documentation build step.
=> Add mkdocs-material[imaging] dependency

docs/annotators.md, supervision/__init__.py, supervision/annotators/core.py
This PR adds the `PixelateAnnotator` class to the `supervision` annotator suite.
You can use the following Colab notebook to test this annotator:
https://colab.research.google.com/drive/1eHmk_5GgdqI2wGj08UZbQ0peNTKVG4b2?usp=sharing#scrollTo=eglvoEdTdAPj
N/A
=> Add `PixelateAnnotator`

docs/detection/utils.md, supervision/__init__.py, supervision/detection/utils.py, test/detection/test_utils.py
Added a new function `scale_boxes` to the detection utilities to scale the dimensions of bounding boxes. This function accepts bounding boxes and a scaling factor as input and returns the scaled bounding boxes. It can enlarge or shrink the input bounding boxes based on the value of the passed factor. The function was also documented in the utils.md file and necessary tests were added to assure its correctness.
=> Add `scale_boxes` function to detection utils

supervision/annotators/core.py
Added necessary logic in TraceAnnotator so that it now respects the position argument. The update now allows all the predefined positions which when passed to modify the tracing position.
Issue: https://github.com/roboflow/supervision/issues/420
`trace_annotator = sv.TraceAnnotator(position=Position.TOP_LEFT)`
https://github.com/roboflow/supervision/assets/33096608/89c53f78-c5b3-413e-9d24-f74aef387265
=> Fixed TraceAnnotator to respect the postion argument.

docs/annotators.md, supervision/__init__.py, supervision/annotators/core.py
Added the ability to draw triangle markers on an image based on the provided detections with the TriangleAnnotator class. This is useful when needing to specifically mark or highlight certain areas of an image. The user can now specify both the color of the annotation and the metrics of the triangle such as base and height, as well as its position.
=> Add `TriangleAnnotator` to annotators

.github/requirements-dev-min.txt, poetry.lock, pyproject.toml, supervision/dataset/formats/pascal_voc.py, test/dataset/formats/test_pascal_voc.py
Based on analysis of Bandit,snyk we have security vulnerability around xml and for that python docs even recommend to use defusedxml 
https://docs.python.org/3/library/xml.html#module-xml
https://docs.python.org/3/library/xml.html#xml-vulnerabilities
https://docs.python.org/3/library/xml.html#the-defusedxml-package
https://github.com/tiran/defusedxml
You can also view vulnerable state in here  
https://www.codefactor.io/repository/github/roboflow/supervision/issues#
This PR fixes xml vulnerability and adding extra rules into bandit for make sure in future we don't effect by XML attacks in anycases.
fix bandit rule B318: (xml-attribute-parsing) defusedxml package should be used to parse untrusted XML data
fix bandit rule B314: (xml-entity-expansion) XML entity expansion should be disabled …
=> feat(xml-parsing): 🔐 enhance security with defusedxml and bandit rules

poetry.lock, pyproject.toml, tox.ini
This commit introduces an initial tox.ini configuration file to the project. The tox.ini file is used to automate testing in multiple Python environments. In this case, it's set up to test across multiple Python versions and with pytest. This is a significant enhancement  as it ensures the codebase works consistently across different Python versions, improving its robustness and reliability.
To test, simply run `tox` in your terminal. Make sure you have `tox` installed in your environment. If not, you can install it using `pip install tox`.
Requirements:
- Python (multiple versions as specified in `tox.ini`)
- tox
- pytest
Also make sure you have multiple version of python in your system properly in this case versions between py3.8 and py3.12
=> feat(tox): ✨ initial tox.ini for testing multiple python versions locally for supervision

supervision/assets/downloader.py
Small fix for hide md5 usage in code analysis but usage is safe (just file integrity check)
=> fix(sec-md5): 🐞 md5 security warning fix

supervision/assets/downloader.py
**MD5 Hashing**: I fixed the `hash_new` function call in the `is_md5_hash_matching` function. Previously, the function was called with two positional arguments, causing a TypeError. The function call has been corrected to first create the hash object and then update it with the file contents. 
Previous (We assume file already downloaded and we do re-check)
```python
from supervision.assets import download_assets, VideoAssets
download_assets(VideoAssets.PEOPLE_WALKING)
```
Error message
```python
>>> download_assets(VideoAssets.PEOPLE_WALKING)
,Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "supervision/supervision/assets/downloader.py", line 82, in download_assets
if not is_md5_hash_matching(filename, …
```
=> fix(md5): 🐞 hash_new param fix for downloaded content check

.github/workflows/test-min.yml, poetry.lock, pyproject.toml
Fixes scipy memory leak vulnerability
=> fix(security): 🔐 bump scipy version for memory leak vulnerability

docs/annotators.md, docs/index.md, supervision/__init__.py, supervision/annotators/core.py, supervision/detection/core.py, supervision/tracker/byte_tracker/core.py
This pull request introduces two significant features:
YOLOv8 Oriented Bounding Box (OBB) Support: This feature extends the capabilities of the YOLOv8 model to detect objects in images and provide oriented bounding boxes as output. This is particularly useful in scenarios where the orientation of the object matters, such as detecting vehicles or buildings from aerial images. The support for OBB allows the model to provide more precise and detailed information about the detected objects.
OrientedBoxAnnotator: This new class provides functionality for annotating images with oriented bounding boxes. This can be used to visually verify the output of the YOLOv8 model with OBB support or to create new training data. The OrientedBoxAnnotator makes it easy to draw oriented bounding boxes on …
=> feat: ✨ yolov8-obb support and OrientedBoxAnnotator added for obb

supervision/dataset/formats/coco.py, supervision/dataset/formats/pascal_voc.py, supervision/dataset/formats/yolo.py
Fix looping over detections in supervision dataset loaders.
=> fix looping over detections in dataset loaders

examples/traffic_analysis/inference_example.py, examples/traffic_analysis/ultralytics_example.py
This pull request addresses an issue within the vectorize function in my specific use case, where sometimes there are no detections on certain frames, leading to errors with inputs of length 0. The fix involves incorporating a pre-check for the input's length to prevent such errors from occurring.
=> Refactor class DetectionsManager to handle empty detections_all array

supervision/detection/line_counter.py, supervision/draw/utils.py, supervision/geometry/core.py
LineZoneAnnotator has two new boolean parameters, display_in_count and display_out_count, to the functions display_in_count and display_on_count. When set to True, these parameters display the input/output values. (Fix: #792)
To optimize performance and avoid unnecessary mathematical calculations when the values are not displayed, I encapsulated these calculations within a separate function.
For testing purposes, please refer to the provided [Colab link](https://colab.research.google.com/drive/1ChKBEtA3ij-Cezf3DKOBoX5rs2VhXGdf?usp=sharing).
-   [x ] New feature (non-breaking change which adds functionality)
Added two boolean parameters, display_in_count and display_out_count, to display_in_count and display_on_count functions.
Implemented conditional logic to display input/output values …
=> LineZoneAnnotator make display of int/out values optional

CITATION.cff, docs/changelog.md
I fixed the small typo errors I found in the documents.
=> Fix typos in the CITATION.cff and changelog.md files

docs/changelog.md, mkdocs.yml, supervision/detection/annotate.py, supervision/detection/core.py, supervision/draw/color.py
Improved communication of deprecated features.
- Created a separate `Deprecated` page `Supervision` docs
- Marked documented deprecated features with the appropriate note 
- Deprecated methods will also continue to log out the deprecation message in the terminal
- Increased deprecation period of all currently deprecated features up to `supervision-0.22.0`
=> improved communication of deprecated features

supervision/detection/line_counter.py
When version 0.18.0 was released, the calculated in/out values in LineZoneAnnotator had been swapped. This issue has been fixed.
resolve #838 
For testing purposes, please refer to the provided [Colab link](https://colab.research.google.com/drive/1ChKBEtA3ij-Cezf3DKOBoX5rs2VhXGdf?usp=sharing).
Example Output: [Google Drive Link](https://drive.google.com/file/d/1d1rImXd0T5zUOnZVPTAU7mvaRidQZD-c/view?usp=sharing)
Please review thank you :)
=> [LineZone] - flip in/out line crossing directions #838

docs/detection/utils.md, supervision/__init__.py, supervision/detection/core.py, supervision/detection/utils.py, test/detection/test_utils.py
This PR introduces Non-Maximum Suppression (NMS) algorithm focused on segmentation, enhancing our object detection capabilities, particularly in segmentation tasks. We have renamed the traditional `non_max_suppression` function to `box_non_max_suppression` for better clarity regarding its application to bounding boxes. Furthermore, we've integrated a conditional mechanism within the `with_nms` function that utilizes segmentation masks for NMS when such masks are present in the predictions. This optimization leverages the spatial context provided by segmentation masks to improve the suppression process.
This enhancement is part of a task segmented into two parts for more focused development and review. This PR addresses the first part, as discussed in the related issue …
=> [NMS] - add segmentation models support

supervision/detection/core.py
resolve #837 
This Pull Request proposes a modification to the from_inference function to ensure it includes the class_name key within Detections.data even when the Roboflow inference result is empty.
For testing purposes, please refer to the provided [Colab link](https://colab.research.google.com/drive/1zfE98kjjyLQDGysUAZhQalQUj3k5aS2L?usp=sharing).
Please feel free to provide any feedback or comments you may have regarding this Pull Request.
=> [Detections] - from_inference should include 'class_name' key in Detections.data even if result is empty #837

docs/notebooks/object-tracking.ipynb
Small fix to object tracking cookbook colab notebook link. was incorrectly pointed to /main. 
Ran `mkdcos serve` and was able to navigated to colab notebook.
=> Fix google colab link in object tracking cookbook

supervision/annotators/core.py
Added Position.CENTER_LEFT
Description:
Summary
This Pull Request introduces support for the CENTER_LEFT text position in the LabelAnnotator class. Previously, the resolve_text_background_xyxy method did not handle CENTER_LEFT, resulting in a None return value and potentially causing errors during annotation tasks.
Changes
Added an additional condition to the resolve_text_background_xyxy method to handle CENTER_LEFT text positioning. This ensures that when CENTER_LEFT is specified as the text position, the method calculates and returns the correct coordinates for the text background.
Included error handling for unsupported text positions to improve code robustness and provide clearer feedback for developers.
Impact
Enhanced Functionality: The LabelAnnotator class can now correctly handle …
=> Add Support for Center Left,Right Text Position for LabelAnnotator

docs/cookbooks.md, docs/javascripts/cookbooks-card.js
- Hide navigation in the cookbook website (we made a decision to hide it)
- Make author avatars work the same way as in OpenAI Cookbooks
- Better fix for author avatars on top of navbar (navbar is `z-index: 5`)
=> new cookbook z-index fix for author avatar

supervision/detection/utils.py
mask_iou_batch may use a large amount of memory when there are hundreds of detections.
For example, [in this discussion](https://roboflow.slack.com/archives/C064XLTESPQ/p1708594206223019?thread_ts=1708034650.943079&cid=C064XLTESPQ), 747 detections result in 120GB allocation, which will fail in most cases.
Tested locally
=> Limit memory usage for mask_iou_batch

.pre-commit-config.yaml, pyproject.toml
```console
isort (pyi)..........................................(no files to check)Skipped
ruff.....................................................................Passed
ruff-format..............................................................Failed
- hook id: ruff-format
- files were modified by this hook
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `pyproject.toml`:
- 'dummy-variable-rgx' -> 'lint.dummy-variable-rgx'
- 'fixable' -> 'lint.fixable'
- 'ignore' -> 'lint.ignore'
- 'select' -> 'lint.select'
- 'unfixable' -> 'lint.unfixable'
- 'flake8-quotes' -> 'lint.flake8-quotes'
- 'pydocstyle' -> 'lint.pydocstyle'
- 'pylint' -> 'lint.pylint'
- 'per-file-ignores' -> …
```
=> ci: 👷 ruff name rules updated

supervision/detection/utils.py
Bugfix mask_iou_batch memory limit 5MB -> 5GB
Change memory_limit unit from Byte to MB
Tested locally
=> Bugfix mask_iou_batch memory limit 5MB -> 5GB

supervision/detection/tools/smoother.py
Addresses issue #928 matching implementation in ByteTrack, but sidestepping the underlying cause outlined in #943.
Smoother takes as input Detections with a defined `tracker_id`, but when no detections are left after smoothing, it would return an object where `tracker_id` is `None`.
When accessing such detections, for example, using `zip(detections.class_id, detections.tracker_id)`, a `NoneType is not iterable` error would be raised.
Similar to implementation of `ByteTrack.update_with_detections()` does it, the `tracker_id` is added explicitly in cases where it's not present already (in fact - only when no detections are left).
Fixes issue: #928
Related Issue: #943
-   [x] Bug fix …
=> Fix smoother removing tracking_id from detections

supervision/detection/tools/polygon_zone.py
This change make PolygonZoneAnnotator count/label visible or not based on option and since default is True this won't be breaking change in new version of when others upgrade too. 
Collab URL : https://colab.research.google.com/drive/1utvUBEPufTl6lG6irMx2lB6h_xMiP3A1?usp=sharing
PolygonZoneAnnotator new param added as doc `display_in_zone_count (bool): Show the label of the zone or not. Default is True`
=> feat(PolygonZoneAnnotator): ✨ make display of zone label optional default is true

supervision/detection/tools/polygon_zone.py, supervision/utils/internal.py, test/detection/test_polygonzone.py
This PR addresses [Issue #844](https://github.com/roboflow/supervision/issues/844).
- Rename `triggering_position` to `triggering_anchors` to be consistent with the `LineZone` naming convention.
- Update type of argument from `Position` to `Iterable[Position]`.
- Maintain the default behavior. The zone should, by default, be triggered by `Position.BOTTOM_CENTER`.
- Adds unit tests for `PolygonZone`.
- Updates documentation.
-   [ x ] New feature (non-breaking change which adds functionality)
-   [ x ] This change requires a documentation update
For a minimalist setup, I'm doing the following:
1- Create mock detections simulating an object moving in a straight line.
2- Instantiate a `PolygonZone` object with polygon partially intersecting the line.
3- Compute the …
=> Polygonzone add multiple anchors support

pyproject.toml
FIxing warning
```console
- hook id: ruff-format
- files were modified by this hook
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `pyproject.toml`:
- 'pylint' -> 'lint.pylint'
1 file reformatted, 88 files left unchanged
```
Organize ruff config bit more to make cleaner
=> ci: 👷 update ruff config and group lint

supervision/detection/tools/polygon_zone.py, supervision/draw/color.py
```
Python 3.10.13 (main, Aug 24 2023, 12:59:26) [Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import supervision as sv
>>>
>>> type(sv.Color.WHITE)
<class 'supervision.draw.color.Color'>
```
Fix: https://github.com/roboflow/supervision/issues/1010
=> feat: 📝 static type improvement color constants and PolygonZone

supervision/tracker/byte_tracker/core.py
This change addresses this issue: (https://github.com/roboflow/supervision/issues/754)
`update_with_detections` now returns the original detections that were tracked by ByteTrack with their original bboxes, masks, class_ids, data fields and with updated track_ids. Detections that were not tracked this frame are not included in the returned detections.
-   [x] New feature (non-breaking change which adds functionality) - Segmentation tracking
I have tested this change by running object tracking for both object detection and segmentation in this [colab notebook](https://colab.research.google.com/drive/1azgc_A-divM3Z5l0TyHW2SRHnw6EUlbO?usp=sharing)
Tracking docs should be updated to reflect that ByteTrack can now do segmentation …
=> Fix issue #754

supervision/annotators/core.py
Implements #1027 
`sv.LabelAnnotator` has a new attributre `corner_radius`.
A new custom method `draw_rounded_rectangle` has been added using almost same arguments with `cv2.rectangle` but using the new `corner_radius` attribute.
Examples using `corner_radius = 8 | 20`, are attached below:
Google Colab ready for testing:
https://colab.research.google.com/drive/1sHdjb1bg8aGekj7uaSNQ80VqhgTzASOs?usp=sharing
When initializing `sv.LabelAnnotator()` the `corner_radius` can be specified using int values. 
-   [ ] Docs …
=> Add `corner_radius` to `sv.LabelAnnotator` to handle roundness of label edges.

.github/workflows/publish.yml
I will re-write this branch part in a better way (I was already testing and there is a couple of problems I am talking with GH people as well)  For now I want to remove fail action part
=> ci: 👷 publish pypi on branch removed

supervision/detection/utils.py
When I tried to use boolean array indexing to get specific detections from a Detections object, the data field sometimes returned the wrong values (everything is the second value) and sometimes it just didn't work. (See issue #1061)
This is an issue I ran into while trying to simplify ByteTrack.update_with_detections(). Boolean indexing is a feature that is commonly used in general and it would be good to ensure Detections works the same way np.arrays and lists work.
I tested this with the same test cases from my bug report. [Colab notebook](https://colab.research.google.com/drive/1nRKhgTnlubPNOtEGZV4QMYffDjI1VxnQ?usp=sharing)
-   [ ] Docs updated? What were …
=> fix Detections.get_data_item() bug (#1061)

supervision/tracker/byte_tracker/core.py
I made a very silly mistake in my PR https://github.com/roboflow/supervision/pull/1035. The enumerate returns and index and a tuple and I was unpacking that tuple incorrectly. I have since re-tested it with this change, and it works correctly now. I also had to fix a bug when there are no existing track_ids.
This colab notebook https://colab.research.google.com/drive/1azgc_A-divM3Z5l0TyHW2SRHnw6EUlbO#scrollTo=J-lQUq30tUgD is what I used to test it.
=> fix enumerate call

supervision/detection/core.py
This PR adds support to the `from_transformers` method to allow getting detections from Segmentation models. At the moment I'm testing the feature by returning the object based on the `boxes` key being present. Processing segmentation models in `transformers` doesn't return the `boxes` key.
```python
import torch
import requests
from PIL import Image
from transformers import DetrImageProcessor, DetrForSegmentation
processor = DetrImageProcessor.from_pretrained("facebook/detr-resnet-50-panop …
```
=> Add segmentation model support to from_transformers

supervision/detection/core.py
Fix issue #8107
Allows you to convert detections from Ultralytics which do not contain the key "obb".
An if statement is added before accessing the "obb" key in the dictionary in order to verify its presence.
The fix was tested with the code snippet provided in the [official documentation](https://supervision.roboflow.com/detection/core/#supervision.detection.core.Detections.from_ultralytics)
No
=> Fixed obb key check in ultralytics_results

supervision/assets/list.py
Adding the beach drone footage to assets as discussed with @SkalskiP
```
from supervision.assets import download_assets, VideoAssets
download_assets(VideoAssets.BEACH)
download_assets(VideoAssets.BEACH)
```
=> Add beach drone footage asset

supervision/keypoint/core.py
Keypoints crash when none are detected.
Uncomment other parts for regression tests on videos.
```python
import numpy as np
import cv2
import requests
from pathlib import Path
from ultralytics import YOLO
from supervision.keypoint.skeletons import Skeleton
from supervision.assets import download_assets, VideoAssets
def download_img(url: str, out_path: Path) -> None:
if out_path.exists():
print(f"File already exists: {out_path}")
return
r = requests.get(url)
with open(out_path, "wb") as f:
f.write(r.content)
model = YOLO('yolov8n-pose')
download_assets(VideoAssets.PEOPLE_WALKING)
img_url = "https://placedog.net/400x400?id=13"
img_path = Path("dog.jpg")
download_img(img_url, img_path)
img = …
```
=> Fix keypoint crash with no detections

examples/count_people_in_zone/inference_example.py, examples/count_people_in_zone/requirements.txt, examples/count_people_in_zone/ultralytics_example.py, examples/speed_estimation/inference_example.py, examples/speed_estimation/requirements.txt, examples/speed_estimation/ultralytics_example.py, examples/speed_estimation/yolo_nas_example.py, examples/time_in_zone/inference_file_example.py, examples/time_in_zone/inference_naive_stream_example.py, examples/time_in_zone/inference_stream_example.py, examples/time_in_zone/requirements.txt, examples/time_in_zone/ultralytics_file_example.py, examples/time_in_zone/ultralytics_naive_stream_example.py, examples/time_in_zone/ultralytics_stream_example.py, examples/traffic_analysis/inference_example.py, examples/traffic_analysis/requirements.txt, examples/traffic_analysis/ultralytics_example.py
Removed the `frame_resolution_wh` parameter in `PolygonZone` from examples. #1109
Tested out a couple of examples, and everything looks good.
=> Update examples to remove `frame_resloution_wh` in [PolygonZone]

supervision/tracker/byte_tracker/core.py
This PR fixes https://github.com/roboflow/supervision/issues/1044. It replaces this PR https://github.com/roboflow/supervision/pull/1050 which caused only one track to be initialized per frame (see the comment)  I decided to re-implement this by instead of setting the tracker_id to -1, I used the existing is_activated property of STrack to mark whether the detection is valid or not. This does not affect the functionality of ByteTrack because every unconfirmed track will get added to the self.tracked_stracks list every time it is matched with a new detection.
I tested this by running writing pytests for ByteTrack …
=> add minimum_consecutive_frames to bytetrack

supervision/tracker/byte_tracker/core.py
Fix issue https://github.com/roboflow/supervision/issues/1164
ByteTrack stores all removed tracklets in a single list. This list grows indefinitely increasing tracking computational cost. 
This PR fixes the issue by restricting the list to tracklets removed in the last pass of the tracker.
Currently, there are no tests for tracking. I've used publicly available tracking videos to test for regression.
=> Fix ever increasing memory consumption in ByteTrack

supervision/detection/core.py, supervision/detection/utils.py, test/detection/test_core.py, test/detection/test_utils.py, test/test_utils.py
* `Detections.merge` now merges detections when some of them are `None` or empty.
* Missing keys in `data` should not be an issue, unless further detections containing new data in those.
* Expanded tests with the new behaviour.
See the tests to see expected behaviour.
:notebook:  [Google Colab](https://colab.research.google.com/drive/1PQ3j_5hAbuh4ivHEsQV8sxKvIVDGK7j7?usp=sharing)
* (Slicer with segmentation model still fails, but with a different error)
* Roboflow model (with `data` is now merged with `Detections.empty` successfully).
* Multiple new tests were written - …
=> More flexibility in Detections.merge 

docs/how_to/detect_small_objects.md
In one docs example, inference slicer callback returns nothing, which would cause an error.
Checked all callback examples - everything else is fine.
Found when I coplied code from [example](https://supervision.roboflow.com/latest/how_to/detect_small_objects/) to [This Colab](https://colab.research.google.com/drive/1heA84CG0Ktb3Gsn3PJ4sIbiiwhKyYiOY?usp=sharing
)
=> Minor docs update: missing return in inference slicer callback

supervision/annotators/utils.py
In `annotators/utils.py` there are some error messages in multi-line strings and produced sentences with some errors in spacing. 
None
YOUR_ANSWER
Space fixes
No need to update.
=> Correct sentence spacing in `annotators/utils.py`

docs/how_to/detect_small_objects.md
Updated docs that did not include a `return` in a slicer callback.
=> Missing return in another slicer callback

docs/utils/draw.md
`calculate_optimal_font_scale` does not exist.
```
<div class="md-typeset">
<h2><a href="#supervision.draw.utils.calculate_optimal_text_scale">calculate_optimal_text_scale</a></h2>
</div>
```
=> docs: calculate_optimal_text_scale, not calculate_optimal_font_scale

supervision/detection/core.py
It fixes #1219.
We added "obb" key check added in #1093 and latest ultralytics package does not have that key.  I changed to "obb" check "and" to "or" and I tested with obb/detection/seg  all of them works.
=> fix: 🐞 yolo obb condition check set or for newer and older version

supervision/detection/utils.py, supervision/tracker/byte_tracker/core.py
This change fixes issue #458. The object tracker was not able to handle detections that had a bounding box area of zero. I fixed this by filtering out the bounding boxes that have an area of zero in `update_with_tensors()`. 
I tested this change by deliberately sending boxes with an area of 0 into the tracker. The tracker was able to handle this by simply ignoring those detections. [Colab notebook](https://colab.research.google.com/drive/1qDtagBbfLHVE8G-VhgBCOiK9H-GTP8c4?usp=sharing) with test code.
=> Fix Cost Matrix containing NaN Values in ByteTrack

supervision/detection/line_zone.py, supervision/detection/tools/smoother.py
I've verified every instance of `tracker_id` in our repo, and found that its **contents** are never `None`.
The checks we have are not necessary.
In cases where `tracker_id` gets `-1` added, it is indeed filtered out very soon.
Basic tests of smoother and line counter can be found here: https://colab.research.google.com/drive/1_gajR0D_CZ4Z2dZ1y8SdVaWGbDZ0mBpl?usp=sharing
Even with no detections for longer periods of time, no errors (and no None values) are produced.
None
=> tracker_id contents are never `None`

supervision/detection/core.py, supervision/utils/internal.py, test/utils/test_internal.py
When checking if both fields are `None` or defined in two detection to be merged, we'd hardcode the fields.
This change allows getting the programmatically.
Note that it requires an instance of the class.
Ran locally, added and ran very basic tests.
Colab: https://colab.research.google.com/drive/193L8OHsEsdhQEenDNwKbGdtPyE68cUbW?usp=sharing
None
=> Dynamically select Detections member variables

supervision/detection/core.py, supervision/detection/utils.py, test/detection/test_core.py, test/detection/test_utils.py
`Detections.merge` creates an invalid `Detections` object when the following are true:
1. Detections 1 have `confidence=None` or `class_id=None`, and is of length > 0.
2. Detections 2 are created with `Detections.empty()`, so have `confidence=np.empty` and `class_id=np.empty`. 
This results in a detection of mixed lengths: `len(xyxy) > 0`, `len(confidence) == 0`.
---
This proposed solution:
1. Adds one test case showing the error
2. Adds a filter discarding empty detections at the start of Detections.merge.
3. Reverts the flexible merging introduced in https://github.com/roboflow/supervision/pull/1177
* I suggest doing a diff with `0.20.0` to check.
1 Test case + Colab: https://colab.research.google.com/drive/1KWsVmbS6pCPdy5yPyHtwi …
=> Revert flexible merging, Filter out empty detections

supervision/detection/line_zone.py, supervision/detection/tools/polygon_zone.py, test/detection/test_line_counter.py, test/detection/test_polygonzone.py
Added unit tests for [LineZone](https://github.com/roboflow/supervision/blob/develop/supervision/detection/line_zone.py#L12C7-L12C15).
-   [x] New unit tests
=> Add LineZone unit tests

docs/cookbooks.md, docs/detection/annotators.md, docs/detection/tools/line_zone.md, docs/detection/tools/save_detections.md, docs/detection/utils.md, docs/how_to/detect_and_annotate.md, docs/how_to/save_detections.md, docs/trackers.md, docs/utils/image.md, docs/utils/iterables.md
1. Removed old "New" tags, added tags to pages with large additions in 0.21.0
2. "crop" -> "scale" in one heading (as two entries for crop were present)
`mkdocs serve` -> 👀 
1. New / old tags
2. crop -> scale in one heading (as two entries for crop were present)
=> Update "New" tags in docs, fixed typo in one heading

poetry.lock, pyproject.toml
As of a few days ago, an error is raised when attempting to load `cv2`, as it does not support numpy `2.0.0`. This results in our CI tests failing and may have consequences for end-users.
Until all our dependencies expand support, let's pin numpy to `<2.0.0`.  
See more: https://github.com/opencv/opencv-python/issues/943#issuecomment-2171817940
1. `pytest` passes
2. `poetry install --with dev` works
3. Verified that changes to the lock file are minimal
4. importing cv2 and numpy work
5. Hopefully CI builds succeeds, unlike in https://github.com/roboflow/supervision/pull/1286
I have not done anything with respect to versioning. We should think about releasing this as `0.21.1`.
=> Numpy upper limit: `<2.0.0`

supervision/annotators/core.py
Adding changes as described in the [ISSUE](https://github.com/roboflow/supervision/issues/1285)
The modifications upon the existing code base might result for a more clear visualisation 
Also adding the [colab](https://colab.research.google.com/drive/1vHUSwxYtMz_wbp7IH18kFlZBD1UZdeYV#scrollTo=Gk2KhyBkw6h6) file for checking and testing.
Thanks.
=> Modified triangle and dot in annotators-core 

README.md
2 links in Readme were broken. This fixes them.
Checked readme page and clicked `datsets` and `annotators` links.
=> Readme: fix broken links

supervision/detection/core.py
Copying segmentation masks from detectron2 predictions to the detection class. The resulting masks can be used for displaying with sv.MaskAnnotator(). 
The code is executed:
detections = sv.Detections.from_detectron2(p_det)
bounding_box_annotator = sv.MaskAnnotator()
annotated_frame = bounding_box_annotator.annotate(
scene=img.copy(),
detections=detections,
)
=> detectron2 mask convert to detection

supervision/annotators/core.py
Fixes #1301 
The overlay_image function in the used in the `CropAnnotator` class [here](https://github.com/roboflow/supervision/blob/f00dcede1a2e0e3bca0f403ed4a0d23e16cde937/supervision/annotators/core.py#L2105) had different parameters as compared to the overlay_image function defined over [here](https://github.com/roboflow/supervision/blob/f00dcede1a2e0e3bca0f403ed4a0d23e16cde937/supervision/utils/image.py#L293). Soo fixed that issue by changing it in the `CropAnnotator` class.
I will update a [colab](https://colab.research.google.com/drive/1P7iwFNeg2uv35ZhqnjXhu6rbPfr …
=> Updated overlay_image function in CropAnnotator

supervision/annotators/core.py, supervision/detection/annotate.py, supervision/keypoint/annotators.py, supervision/utils/conversion.py, supervision/utils/image.py, test/utils/conftest.py, test/utils/test_conversion.py
This is a 3-in-1:
1. Addressed faults with RichLabelAnnotator left after #1116 
* Primarily: it would not convert back to `np.ndarray` after annotation
2. Realized many annotators do nothing when used in-place.
* Description on [Loom](https://www.loom.com/share/91308392c7de44ce9ad115778bc99c42?sid=8279b66f-4786-42de-9e77-58cd7381f6be)
* Fixed in [Colab](https://colab.research.google.com/drive/1NvVs28MnSb-_W-zkFa6-FXiY-0G4nx7k#scrollTo=dVZIKNV1uXVl)
3. Color Annotator would fill boxes with solid color if used in-place, with numpy.
Ran every annotator except for TraceAnnotator.
Ran tests.
Colab: …
=> Patch RichLabelAnnotator, fix in-place functionality of other annotators

supervision/keypoint/core.py, supervision/validators/__init__.py
This PR adds support for keypoints support for detectron2 model
https://colab.research.google.com/drive/19nA7-MZQbPPMhtBbpMEpmRcpemwqSatJ?usp=sharing
=> feat: 🚀 Keypoint support for detectron2 

supervision/detection/lmm.py, test/detection/test_lmm_florence_2.py
Florence 2 would previously return normalized xyxy regions. It should be corrected to box coordinates.
Tested in Colab: https://colab.research.google.com/drive/1Lq9LcIVlgVlUpHDBKcVYbXp7ZuY20K7g#scrollTo=P_Vkd5gcxbqW
Change any Colabs where boxes are explicitly de-normalized.
=> Fix bug where florence2 returns normalized xyxy regions

README.md, docs/index.md, mkdocs.yml
Supervision cheatsheet was previously only posted on LinkedIn.
This change adds mention to it in supervision docs:
1. Readme
2. Nav bar (top bar)
3. Quickstart Cards at the bottom
mkdocs serve
Added cheatsheet to:
1. Readme
2. Nav bar (top bar)
3. Quickstart Cards at the bottom
=> Add cheatsheet links in supervision docs, readme

.github/workflows/notebook-bot.yml
Idea : Any of our pull request has notebook edit or create change(s) we can review easily with single click with colab or reviewnb (login required)
=> ci: 👷 check notebook and automatically create colab link and show better difference in reviewNB

supervision/draw/color.py
Fix for https://github.com/roboflow/supervision/issues/1369.
Google Colab https://colab.research.google.com/drive/1cRxvuuJe8jrQYt8kepwUGRcAU80T9N-y?usp=sharing testing the change.
=> fix `from_matplotlib` when Matplotlib colormaps does not provide `colors` property

supervision/annotators/core.py
`CropAnnotator`'s `scale_factor` is an int vs a float. It's [passed to `scale_image` here](https://github.com/roboflow/supervision/blob/e76dec7e1518cd286ea7391caf3a5766bbda1890/supervision/annotators/core.py#L2194) and that [accepts a float](https://github.com/roboflow/supervision/blob/65f2bbba5792257214bda8c812b2bd02c1710e1d/supervision/utils/image.py#L90).
Using a float is useful since it'll let you scale down (or up by less than 2x). This functionality already works, the type annotation is just wrong.
[In this Colab notebook](https://colab.research.google.com/drive/1RDRFDOW90EyQsMuJLZThHLgPhGhoCTDs#scrollTo=EGUKXHHzXp3P).
No
-   [x] Docs updated? What were the changes: type annotations
=> Change CropAnnotator scale_factor from int to float

supervision/detection/tools/inference_slicer.py, supervision/detection/utils.py
Issue: draw wrong OrientedBoxAnnotator with InferenceSlicer #1339
Resolution: create function *utils:move_obb_boxes (as suggested by LinasKo), with a call inside *tools/inference_slicer:move_detections
No new dependencies required
created detection-like object (single and multiple detections) based on the submitted issue, passed to the function and verified results
I did not change any documentation
=> Move OBB boxes

poetry.lock, pyproject.toml
I made extra bit of research and I notice it was actually happening because of lack of numpy version poetry locked in toml file so I set min and max for py10 and version for py10 above (I set to first py11 supported version as min since it is the first version has wheels for py11) 
Fix: #1378 
I tested with tox and with poetry(py8,py9,py10,py11,py12)
=> fix: 🐞 poetry numpy version has been set based on python version

supervision/keypoint/annotators.py
Fix: Text is not vertically centered inside text box. 
=> fix `VertexLabelAnnotator` text position within text box

docs/detection/annotators.md
Fix typo in RichLabelAnnotators https://supervision.roboflow.com/latest/detection/annotators/#__tabbed_1_14 where variable name label label_annotator is corrected to rich_label_annotator.
Followed the procedure using mkdocs to serve the documentation locally.
=> Fix typo in RichLabelAnnotator docs

supervision/annotators/core.py
Fix of issue #1384 
I will update with colab notebook once the changes are approved.
=> Added Union[Color, ColorPalette] to text_color parameter

supervision/metrics/detection.py
[Supervision 0.22.0](https://supervision.roboflow.com/latest/changelog/#0220-jul-12-2024) introduced dataset lazy loading, allowing to load the images into memory only when necessary. Considering this, the `images` property in datasets classes will be deprecated in version 0.26.0, as it loads all images into memory.
This PR replaces the deprecated `for img_name, img in dataset.images.items():` present in the `benchmark` method of the `ConfusionMatrix` and `MeanAveragePrecision` classes for the recommended `for path, image, annotation in dataset:` loop.
After the code changes, the `benchmark` method of the `ConfusionMatrix` and `MeanAveragePrecision` stopped printing a deprecation warning, as it does not call the `dataset.images` …
=> Refactor the metric benchmarks to use dataset lazy loading

supervision/utils/notebook.py
Ever so slightly less confusing, as `plot_image` size is in inches.
YOUR_ANSWER
=> specify that plot_image size is in inches

docs/detection/annotators.md, supervision/__init__.py, supervision/annotators/core.py
This PR adds a new `sv.BackgroundColorAnnotator` that highlights all regions outside of a list of bounding boxes or masks.
You can test this feature using the following Colab:
https://colab.research.google.com/drive/18GLw4TR-au9DUmAeWU30M7BFJ_00BlxO?usp=sharing
N/A
N/A
=> Add BackgroundColorAnnotator

supervision/detection/overlap_filter.py, supervision/detection/tools/inference_slicer.py
- Deprecate the `overlap_ratio_wh` argument
- Introduce the `overlap_wh` argument
- Rename the `overlap_filter_strategy` argument to `overlap_filter`
=> refactor `InferenceSlicer` overlap logic

.pre-commit-config.yaml, supervision/detection/core.py
Fixes issue noted in #1453 .
Added brief check and fill of necessary fields in sv.Detections()
**No new dependencies**
Colab attached for testing
-   [ ] Docs updated? **Not needed**
Colab notebook for testing: https://colab.research.google.com/drive/10aRaBAfb__xrMeBNn9amYwrKgcnbExBn?usp=sharing
=> Add ultralytics SAM support when using `bboxes` and `points` arguments in `SAM().predict()`

supervision/annotators/core.py
This PR introduces a new outline_color argument to the TriangleAnnotator and DotAnnotator classes, allowing users to customize the outline color when rendering annotations. Previously, while users could set outline_thickness to render an outline, the color was not configurable. With this enhancement, outline_color can now be set and will integrate seamlessly with the existing color_lookup system, accepting values of type Union[Color, ColorPalette].
Key Changes
Added outline_color argument to TriangleAnnotator and DotAnnotator.
Integrated outline_color with the existing color_lookup mechanism.
resolve https://github.com/roboflow/supervision/issues/1403
For testing purposes, please refer to the provided [Colab link](https://colab.research.google.com/drive/1Wz66ql9LsH-PsTOwg8JlmpSSHOn9fOQV?us …
=> [TriangleAnnotator, DotAnnotator] - allow customization of the contour color #1403

docs/how_to/track_objects.md
fix typo of url 'how_to/detect_and_annotate' to '/how_to/detect_and_annotate'
fix relative link by adding '/' to connect correct document page.
from 'how_to/detect_and_annotate' to '/how_to/detect_and_annotate'
previous was connected to 
`https://supervision.roboflow.com/latest/how_to/track_objects/latest/how_to/detect_and_annotate/#load-predictions-into-supervision`
and now, it indicate right …
=> fix typo in url

supervision/utils/video.py
For some videos, e.g. the one in #1345, the frame generator generates no frames. This happens when `video.get(cv2.CAP_PROP_POS_FRAMES, x)` is called, even when `x = video.get(cv2.CAP_PROP_FRAME_COUNT)`.
Since we use this to skip the first N frames, we can do it manually instead by retrieving and dropping them.
This has the potential to affect many codebases, so thorough tests are needed.
At the very least. this should work on:
1. Videos in` supervision.assets`
2. ~~Videos in #1345~~ Already tested.
3. 5 videos from different online sources, ideally with different video formats.
4. Bonus: I had some GoPro videos that had invalid frames at the start. I should test with those.
Tested …
=> Change how frames are skipped in the generator

docs/detection/utils.md
Edit the title and the content to match each other.
document changes
match content to title, and change order of 'contain_holes' title.
Thanks for your hard effort🙇‍♂️
=> match the titles and the contents

supervision/utils/video.py
Rename `manual_seek` to `iterative_seek`.
Tested docs.
=> rename manual_seek to iterative_seek

docs/detection/annotators.md, examples/count_people_in_zone/inference_example.py, examples/count_people_in_zone/ultralytics_example.py, examples/time_in_zone/utils/timers.py, supervision/annotators/core.py, supervision/dataset/core.py, supervision/dataset/formats/pascal_voc.py, supervision/dataset/formats/yolo.py, supervision/detection/core.py, supervision/detection/overlap_filter.py, supervision/detection/tools/polygon_zone.py, supervision/detection/utils.py, supervision/draw/utils.py, supervision/keypoint/annotators.py, supervision/keypoint/core.py, supervision/metrics/detection.py, supervision/tracker/byte_tracker/core.py, supervision/utils/image.py, supervision/utils/internal.py, supervision/utils/video.py, test/dataset/formats/test_yolo.py
MyPy was showing many issues in the `keypoints/annotators.py` and `annotators/core.py`, so I cleaned it all up.
Where the issues branched into other files, I likewise mopped it up. Here's a [Loom](https://www.loom.com/share/32cd83216e8742e5b56e0567756e5a5c?sid=6789b55e-bbcc-4c50-a19e-984e01096fea). I strongly suggest reviewing one commit at-a-time.
Lastly, there are a few minuscule miscellaneous fixes.
Fixes:
1. Changed a few return types from `np.array` to `np.ndarray`.
2. VSCode's mypy would always highlight `Color.X` and `ColorPalette.X` in red, as it would see it as having type `classproperty`. Changed it so it correctly sees `Color` and `ColorPalette`.
3. We have many variables marked optional. Now, in annotators, they're all the same - marked `Optional[dtype]` if and only if they …
=> Annotator types and docs: MyPy, consistent 'optional', small tidy-ups

.pre-commit-config.yaml, demo.ipynb, poetry.lock, pyproject.toml, test/annotators/test_utils.py, test/dataset/formats/test_pascal_voc.py, test/dataset/test_core.py, test/dataset/test_utils.py, test/detection/test_core.py, test/detection/test_csv.py, test/detection/test_json.py, test/detection/test_line_counter.py, test/detection/test_polygonzone.py, test/metrics/test_detection.py, test/test_utils.py
This changes also introduce enablement of extra ruff rules as well
- https://docs.astral.sh/ruff/rules/#flake8-quotes-q
- https://docs.astral.sh/ruff/rules/#flake8-builtins-a
- https://docs.astral.sh/ruff/rules/#warning-w
- https://docs.astral.sh/ruff/rules/#isort-i
- Yanked setuptools version fixed in lock files.
This changes introduce small fixes but there are other rules I would like to enable in time slowly transition comply better to pep and other python guideline rules as well. 
Thank you.
=> formatter: 🔧 improvements for pre-commit and ruff also apply minor mypy/pep fixes

README.md
fix: Correct typo in link URL from "disuss.roboflow.com" to "discuss.roboflow.com"
I tried opening the misspelled link. It did not open. I corrected the spelling. The link then opened. Solid testing.
No.
-   [ X] Docs updated? What were the changes: the doc itself.
=> fix: correct typo in URL

supervision/metrics/mean_average_precision.py
COCO 101 point Average Precision algorithm previously interpolated the precision values, causing skew in the precision line.
Now, we're integrating over the max precision value seen up to a given recall level.
Multiple notebooks, primarily [this](https://colab.research.google.com/drive/14HwizZFK8vFhiiuiTxH2chN55kI5gEgA?usp=sharing).
=> 101 AP algo: do not interpollate precision

pyproject.toml
Removing old black config (we are covering via ruff)
=> chore: 🧹 old black config removed

demo.ipynb, examples/traffic_analysis/inference_example.py, examples/traffic_analysis/ultralytics_example.py, pyproject.toml, supervision/detection/core.py, supervision/detection/line_zone.py, supervision/detection/lmm.py, supervision/detection/overlap_filter.py, supervision/detection/tools/csv_sink.py, supervision/detection/tools/json_sink.py, supervision/detection/tools/smoother.py, supervision/keypoint/core.py, supervision/keypoint/skeletons.py, supervision/metrics/detection.py, test/dataset/formats/test_coco.py
I added "ruff" formatting rule to be enabled (https://docs.astral.sh/ruff/rules/#ruff-specific-rules-ruf)
References
https://peps.python.org/pep-0448/
https://docs.astral.sh/ruff/rules/unnecessary-iterable-allocation-for-first-element/
https://docs.astral.sh/ruff/rules/mutable-class-default/
=> refactor: ✨ ruff rules enabled and fixed and code refactor made

supervision/draw/color.py
For downstream use being able to determine how many colors are in a ColorPalette object can be useful. E.g., checking if a user has provided a color palette that matches the number of labels. ColorPalette doesn't currenly have a __len__ attribute meaning that `mypalette.colors` has to be used for calculating lengths. This change adds `__len__` to make this more intutitive by allowing `len(mypalette)`.
We found the lack of this functionality confusing: https://github.com/weecology/DeepForest/issues/790
I built the package with the change and confirmed that `len(mypalette)` returns the appropriate result
No associate docs changes
=> feat: add __len__ to ColorPalette

docs/detection/annotators.md
- Adds basic embedded workflow widget to try supervision annotators on annotators docs page.
Demo: https://supervision-dev-joao.ngrok.io/detection/annotators/
The branch is served in https://supervision-dev-joao.ngrok.io/detection/annotators/, you can try it out.
=> Update docs: adds basic workflow to try supervision annotators on annotators doc page

.github/workflows/publish-test.yml, .github/workflows/publish.yml
Pypi username / password has been replaced to with pypi token
=> ci: 👷 pypi username - password swap with token

CODE_OF_CONDUCT.md, docs/detection/tools/line_zone.md, supervision/__init__.py, supervision/detection/line_zone.py
This PR adds per-class counting capabilities to `LineZone`.
The results can be visualized with the newly added `LineZoneAnnotatorMultiClass`.
Rigorously tested locally.
[Colab](https://colab.research.google.com/drive/1IZgu1GUR9Ek-WZeU_1kaYEFhZvCrsPoO?usp=sharing)
Known issues that are NOT to be addressed as part of this PR:
1. Table isn't the best-looking. We can experiment with Pillow in the future.
2. The table only caters to LineZone, whereas tools like PolygonZone may also want to write into it.
3. The list of arguments is dauntingly large.
4. The text may overflow - both horizontally and vertically
5. There's no blacklist or whitelist for displayed classes.
-   [x] Docs …
=> Add per-class counting to LineZone, create LineZoneAnnotatorMulticlass

docs/changelog.md, supervision/detection/tools/inference_slicer.py, test/detection/tools/test_inference_slicer.py
Issue #1543
Changed the default value of the `overlap_ratio_wh` argument to None, as this parameter will be deprecated in version 0.27.0. This change allows a smoother transition by not forcing users to explicitly set it to None.
⚠️ However, this may impact users who were relying on the default value of `overlap_ratio_wh` being `(0.2, 0.2)`. They will now need to explicitly specify this value if they still wish to use it, as the default is now set to None.
I have initiated a new test suite for this class (this is a first step). The tests cover validation of the overlap arguments (`overlap_wh` and …
=> fix: InferenceSlicer overlap_ratio_wh argument changed to None by default

.github/workflows/publish-dev-docs.yml, .github/workflows/publish-release-docs.yml, .github/workflows/test-doc.yml, poetry.lock, pyproject.toml
Temporary fix for mkdocs-git-committers-plugin-2 bug for avoid documentation build failds
=> fix: 🔥 downgrade mkdocs-git-committers-plugin-2 to version 2.3.0

.github/workflows/publish-dev-docs.yml, .github/workflows/publish-release-docs.yml, .github/workflows/test-doc.yml, poetry.lock, pyproject.toml
Based on new release of mkdocs-git-committers-plugin-2 I am reverting to original state of package version
https://github.com/ojacques/mkdocs-git-committers-plugin-2/pull/73
https://github.com/ojacques/mkdocs-git-committers-plugin-2/releases/tag/2.4.1
=> Revert "fix: 🔥 downgrade mkdocs-git-committers-plugin-2 to version 2.3.0"

supervision/metrics/mean_average_precision.py
Fix division to avoid cases where mAP value of `1.01` is possible.
Discovered here: https://colab.research.google.com/drive/10EaQ4lJNXzcmub7doO2vGn2t1LgDdkcC?usp=sharing
This effects mAP scores computed previously, such as those on the leaderboard.
This is effectively a `* 0.99` multiplier and will have a very minimal effect. I don't think we should recompute right now, and instead do it when we have more metrics.
=> Minor fix: mAP can be 1.01

supervision/metrics/__init__.py, supervision/metrics/core.py, supervision/metrics/mean_average_precision.py
This pull request fixes the issue with the class_agnostic argument in the `MeanAveragePrecision` class, which was previously not functioning correctly. `The class_agnostic` flag now treats all predictions and ground truth as belonging to the same class when set to `True`. Added a `_match_detection_batch_class_agnostic` functionality.
[link for collab](https://colab.research.google.com/drive/10EaQ4lJNXzcmub7doO2vGn2t1LgDdkcC?usp=sharing)
-  [X] Bug fix (non-breaking change which fixes an issue)
This fix has been thoroughly tested using newly added unit tests, covering the following scenarios:
1. **Class-Specific mAP Calculation**:
- Verified that mAP is computed correctly when `class_agnostic` is set to `False` (default).
2. **Class-Agnostic mAP …
=> Bugfix: Class-agnostic mAP

.github/workflows/test.yml, tox.ini
=> ci: 👷 python3.13 ci tests and tox ver added

supervision/detection/tools/polygon_zone.py, supervision/draw/utils.py
Default Colors Added: Default colors were added to utility functions such as drawLine, drawRectangle, drawPolygon, and PolygonZoneAnnotator.
Documentation: Documentation was added to explain the changes and usage of the new default colors.
Fix: #1587
- New feature (non-breaking change which adds functionality)
=> feat: 🚀 Add default color to PolygonZoneAnnotator, drawing functions

.github/workflows/poetry-test.yml, poetry.lock, pyproject.toml
Proper python3.13 support configuration and scipy, numpy version enforced to use supported py3.13 package
=> feat: 🚀 python3.13 support for poetry and library

supervision/tracker/byte_tracker/basetrack.py, supervision/tracker/byte_tracker/core.py, supervision/tracker/byte_tracker/matching.py, test/tracker/test_byte_tracker.py
`BaseTrack` implementation includes `_count` class var, similarly `STrack` implementation includes `_external_count` class var. This results in undesirable behavior when running more than one tracker in the same process. In [inference](https://github.com/roboflow/inference/pull/642) we added a block wrapping ByteTrack, if more than 1 video is processed, objects across videos will receive non-deterministic track IDs.
In this change class vars are removed and track ID assignment is handled by upper layer (`ByteTrack`)
Added unit test to cover this scenario.
N/A
N/A
=> let ByteTrack to maintain track ID per instance

supervision/tracker/byte_tracker/core.py
**_Description:_**
This PR modifies ByteTrack to handle detections that do not include a class_id, improving the flexibility of the tracking algorithm. In cases where models don’t return a class_id, ByteTrack will now assign a default internal ID to ensure continued tracking.
**_Key Changes:_**
Default class_id Assignment:
- If class_id is missing from the detection, a default value of -5 is assigned to all detections.
- If class_id is available, the algorithm uses it as normal.
This ensures that ByteTrack works seamlessly with models that do not provide class_id, without breaking existing functionality.
You can test the functionality with the provided [Colab Notebook](https://colab.research.google.com/drive/1SXZndmumMotpHobM3kTefuv2pkggyy_R?usp=sharing) which demonstrates ByteTrack …
=> feat(ByteTrack): Allow ByteTrack to track detection without class ids

supervision/tracker/byte_tracker/core.py
Reverts roboflow/supervision#1618, as class_id is not necessary for tracking.
=> Revert "feat(ByteTrack): Allow ByteTrack to track detection without class ids"

supervision/tracker/byte_tracker/core.py
Resetting the tracker would fail. This was noticed on Develop.
YOUR_ANSWER
=> Bugfix: Tracker reset fails

supervision/tracker/byte_tracker/core.py
Apparently, external track ID must start with `1` and not `0`.
I introduced the regression when refactoring how IDs are stored and generated inside ByteTrack, somewhere around  Commit `#4a7d9cea`.
If this is not true, when `minimum_consecutive_frames > 1`, all objects where no traces are established get assigned an ID of 0, and are connected with a single trace. A bit odd. Not sure where this coupling comes from.
[Colab](https://colab.research.google.com/drive/1YL-NQPRDvJZHh-YQF-Ir8g0LiCoR5u5f?usp=sharing)
None
=> Fix regression where all uninitialized tracks are connected

supervision/dataset/utils.py
fix: 🐞 Remove lowercase conversion for unique class names in merge_class_lists function
Fix: #1641
=> fix: 🐞 Remove lowercase conversion for unique class names in merge_class_lists function

supervision/utils/video.py
It's annoying to have to find `video_info` when using VideoSink. This PR adds a way to automatically determine it.
Will immediately use it in other PRs. Hacky, but I need it fast.
=> VideoSink automatically infers video_info

supervision/assets/list.py
Add a video asset of a skier, with the camera following him.
Video by Adrien JACTA: https://www.pexels.com/video/ski-montagne-skier-piste-de-ski-4274798/
from [Pexels](https://www.pexels.com/)
```python
from supervision.assets import download_assets, VideoAssets
from supervision.assets.list import VIDEO_ASSETS
from supervision.assets.downloader import is_md5_hash_matching
download_assets(VideoAssets.SKIING)
assert is_md5_hash_matching("skiing.mp4", VIDEO_ASSETS[VideoAssets.SKIING.value][1])
```
None
=> Add skiing video asset

docs/how_to/track_objects.md, docs/utils/datatypes.md, mkdocs.yml, supervision/__init__.py, supervision/detection/tools/polygon_zone.py, supervision/keypoint/core.py, supervision/utils/datatypes.py
The simplest way to implement keypoint tracking is to reuse the functionality in detections. In this PR I add:
* `keypoints_to_detections` function for converstion between the two types
* Docs, guides and examples how keypoint tracking can be done
Minors changes:
* Added `KeyPoints.is_empty()`
* typo & format fixes
🟢 This approach does not lock us in whatsoever - we can easily introduce a better tracking system later, without deprecations.
https://github.com/user-attachments/assets/d13af840-4919-4ba8-b86e-d4c620cb67a4
1. Tested in Colab: …
=> `keypoints_to_detections` and Keypoint tracking

docs/metrics/f1_score.md, docs/metrics/mean_average_precision.md, docs/metrics/mean_average_recall.md, mkdocs.yml, supervision/metrics/__init__.py, supervision/metrics/mean_average_recall.py, supervision/metrics/recall.py
Implemented the mAR metric.
The values are uncannily similar to those provided by Torchmetrics, yet diverge by up to `0.1` sometimes. My impression is, it happens when there's more objects / classes missing or perhaps when results are 0.
Colab: https://drive.google.com/file/d/1IUtJzj7Y6Qb4W3jv1SwhkkMygsyGq4zT/view?usp=sharing
-     * Added mAR section, examples, docstrings, images of plots.
=> Mean Average Recall (mAR) metric

supervision/annotators/core.py, supervision/detection/utils.py, supervision/keypoint/annotators.py
Resolved issue #1383 regarding overlapping labels in output.
Changes Done in VertexLabelAnnotator, LabelAnnotator and RichLabelAnnotator
No Extra dependencies used
Have added an optional argument to the VertexLabelAnnotator called `use_smart_positioning` which defaults to `False`.
Enabling this prevents overlapping.
Before:
https://github.com/user-attachments/assets/2906efd5-2a88-4ee0-ba86-cfb250d3fc8f
After:
VertexLabelAnnotator:
https://github.com/user-attachments/assets/5c4bf897-a695-4b88-962e-217f881248fe
Label Annotator:
https://github.com/user-attachments/assets/8ded0d84-cca0-4c05-8504-f1478ac20771
Rich Label Annotator …
=> Added smart positioning (non overlapping labels) to VertexLabelAnnotator

docs/assets.md, poetry.lock, pyproject.toml
chore: 📦 assets extra removed and merged in to main supervision
=> chore: 📦 assets extra removed and merged in to main supervision

pyproject.toml
* Adjustments to numpy version requirements, making supervision easier to integrate with [inference](https://github.com/roboflow/inference) and workflows.
* removed `supervision[assets]` extra - assets are now part of the main `supervision` package.
=> bump version from 0.25.0 to 0.26.0rc1

test/detection/tools/test_inference_slicer.py
Fixing warnings 
```console
========================================================================== warnings summary ===========================================================================
test/detection/tools/test_inference_slicer.py::test_inference_slicer_overlap[slice_wh0-overlap_ratio_wh0-None-None-exception0]
test/detection/tools/test_inference_slicer.py::test_inference_slicer_overlap[slice_wh2-overlap_ratio_wh2-None-None-exception2]
test/detection/tools/test_inference_slicer.py::test_inference_slicer_overlap[slice_wh4-overlap_ratio_wh4-overlap_wh4-expected_overlap4-exception4]
test/detection/tools/test_inference_slicer.py::test_inference_slicer_overlap[slice_wh6-overlap_ratio_wh6-None-None-exception6]
```
fix(tests): 🐞 update inference slicer tests to new overlap system for …
=> fix(tests): 🐞 update inference slicer tests to new overlap system for removing test warnings

.pre-commit-config.yaml, CONTRIBUTING.md, docs/index.md, examples/count_people_in_zone/README.md, examples/heatmap_and_track/README.md, examples/speed_estimation/README.md, examples/time_in_zone/README.md, examples/tracking/README.md, examples/traffic_analysis/README.md
docs: 📝 git clone methods are extended and shallow copy method also added
-   [X] Docs updated? What were the changes: Contributor guide changed
=> docs: 📝 git clone methods are extended and shallow copy method also added

supervision/detection/core.py
Specified that mask is in bool datatype. Used int8 (gpt generated code) and was debugging this issue for 3 hours until I looked into source code of mask annotator.
When using int8 mask (instead of bool dtype), mask annotator will take crazy long to process (like 10sec on MacBook M2), and result won't be correct.
-   [x] Documentation update
Docs update
=> Mask datatype specify in docs

docs/how_to/benchmark_a_model.md, mkdocs.yml
Adding a How-To guide for model benchmarking, along with a [Colab version](https://colab.research.google.com/drive/1HoOY9pZoVwGiRMmLHtir0qT6Uj45w6Ps#scrollTo=eLnLRcRotv6D).
This is the most extensive guide to date, but I expect we'll shorten it somewhat & update it soon with new functionality (Annotator, class remapping function).
Temporarily relies on a specific branch in `inference`.
Ran with both Inference and Ultralytics, 
Temporarily relies on a specific branch in `inference`, checked out the looks with `mkdocs`.
=> How To Benchmark Models

docs/index.md
This change introduce alternative installation methods of supervision for show audience other tooling too.
=> docs: 📝 extend supervision installation methods

supervision/detection/core.py, test/detection/test_core.py
Hopefully fixes #1694.
Test code:
```python
import numpy as np
CLASSES = [0, 1, 2]
prediction = sv.Detections.empty()
prediction = prediction[np.isin(prediction["class_name"], CLASSES)]
print(prediction)
```
New output:
```
Detections(xyxy=array([], shape=(0, 4), dtype=float32), mask=None, confidence=array([], dtype=float32), class_id=array([], dtype=int64), tracker_id=None, data={}, metadata={})
```
=> fix: is_empty check for filtering

supervision/detection/core.py, supervision/keypoint/core.py
Simplified `from_inference` logic. If a user forgets to call `.json()` on a deployed model result, `from_inference` will do it automatically. 
Colab: https://drive.google.com/file/d/1E4a9u75tnOMTq1QX5P7MtJw89S877fYr/view?usp=sharing
=> from_inference now supports roboflow results without json()

mkdocs.yml
This is a tiny change that removes duplicate initialization of the Kapa widget.
With duplicate initialization no Roboflow logo is displayed on the chat button, and attempts to chat with the agent result in a configuration error message.
Tested by checking out mkdocs and chatting with the agent.
=> Kapa: remove duplicate initialization

docs/detection/annotators.md, supervision/__init__.py, supervision/annotators/core.py, supervision/detection/utils.py
`ComparisonAnnotator` enables comparing of two Detections objects, highlighting the difference. It's useful for both model-model and prediction-target comparison.
Features:
* `ComparisonAnnotator` itself
* `ComparisonAnnotator` automatically selects whether obb, mask or xyxy should be used.
* If labels are specified, text boxes with color markers will be drawn
* Only one parameter is required to modify label size - no need to think about text thickness, font, etc
* `xyxy_to_polygons` utils function
* Colab: https://colab.research.google.com/drive/1jyGF5cwxrbqrLs4ZFTIeBMa …
=> Add `ComparisonAnnotator`, `xyxy_to_polygons`

supervision/assets/downloader.py
The dependencies are part of the main supervision package already, as of #1672 
=> Remove import check for `assets`

mkdocs.yml
We've recently created a supervision config in Kapa, which made the widget appear on the site, prior to any testing we could do. Let's disable it until `0.27.0`.
`mkdocs serve`
`Ask AI` widget is no longer available.
=> Disable kapa until we test its functionality

.github/workflows/publish-docs.yml
Fix release docs workflow. Copy and paste error added in an extra `)` that caused the workflow to not run.
=> Fix release docs workflow file

mkdocs.yml
⚠️ Only merge this after 0.26.0 release
Kapa AI abruptly appeared on supervision after setting up the project on Kapa's website, without sufficient testing. We've disabled it for `0.26.0`.
Let's re-enable it for `0.27.0`.
`mkdocs serve`
Only merge this after 0.26.0 release.
`Ask AI` button is available again.
=> Enable kapa for 0.27.0

supervision/keypoint/core.py
Updated the docstring to accurately reflect the correct order of parameters defined in the documentation, ensuring clarity and consistency.
No tests seem to be required
=> correct docstring to match parameter order as per documentation.

docs/detection/utils.md, supervision/__init__.py, supervision/detection/utils.py, supervision/keypoint/core.py, test/detection/test_utils.py
[![Open in Colab](https://img.shields.io/badge/Open%20in-Colab-blue?logo=googlecolab)](https://colab.research.google.com/drive/13cB1KVtjBM4uPYZstcel4KY1yeclpfTS?usp=sharing)
- 🆕 **Bounding Box Conversion**  
- Added `xyxy_xywh` function to convert bounding box coordinates from `(x_min, y_min, x_max, y_max)` format to `(x, y, width, height)` format.  
- 📍 **Location:** `supervision/detection/utils.py`
- 🆕 **Transformers Model Integration**  
- Introduced `from_transformers` class method in `supervision/keypoint/core.py`.  
- Enables creating `KeyPoints` objects from Transformers inference results.  
- 📝 Includes detailed documentation and usage examples.
- ✅ Updated `supervision/__init__.py` to include the `xyxy_to_xywh` function in imports.  
- ✅ Added `xyxy_to_xywh` to the `__all__` list …
=> feat: ✨ Add xyxy_xywh function and from_transformers method for KeyPoints class added

supervision/annotators/core.py
Replaced `np.zeros()` and subsequent fill operations with `np.full()`. This improves performance of the operation on a 1920x1080 frame by ~16x.
-   [x] Performance improvement
Tested running in a loop using `time.perf_counter()` the default implementation with the updated one
Results are average over 10000 iterations
- with 3840x2160 frame: default takes average of 62ms, improved takes average of 5ms. Improvement of 11.5x
- with 1920x1080 frame: default takes average of 16ms, improved takes average 1ms. Improvement of 16x
- with 1280x720 frame: default takes average of 8ms, improved takes average 0.3ms. Improvement of 22.5x
All comparisons have been performed on the same hardware.
No additional requirements
=> perf: improved hsv color mapping in HeatMapAnnotator by 20x

supervision/utils/video.py
This PR adds 2 quality-of-life updates for `sv.process_video`:
1. A parameter called `max_frames` that can be used to limit the maximum number of frames to process in a video.
2. A parameter called `show_progress` that when `True`, shows a progress bar during the video processing loop. Another parameter called `progress_message` can be used to set the message displayed on the progress bar.
The PR can be tested with the following code snippet:
```python
import numpy as np
from ultralytics import YOLO
from supervision.assets import …
```
=> feat(supervision): Add frame limitations + progressbar for `sv.process_video`

mkdocs.yml
feat(mkdocs):  📝 add options for root heading and pygments language class in markdown extensions
Example look
=> feat(mkdocs):  📝 add options for root heading and pygments language class in markdown extensions

supervision/__init__.py
Commit **5d6ad66** introduced the helper `xyxy_to_xcycarh`, but `__all__` still exported
`xyxy_to_xyah`. As a result, `from supervision import *` raises an `ImportError`.
---
* `supervision/__init__.py`  
* Replace the wrong entry **`xyxy_to_xyah`** with **`xyxy_to_xcycarh`**.
---
* **pytest** – full test suite passes.
* Quick sanity-check:
```python
assert all(hasattr(sv, n) for n in sv.__all__)
```
→ no missing symbols.
---
=> fix: typo in __all__ (xyxy_to_xcycarh)

supervision/dataset/core.py
The `DetectionDataset.images` property will be removed in `supervision-0.26.0`. Please loop over images with `for path, image, annotation in dataset:`, as that does not require loading all images into memory.
=> deprecate(supervision): DetectionDataset.images

supervision/metrics/mean_average_precision.py, test/metrics/test_mean_average_precision.py
This PR fixes an issue where Mean Average Precision (mAP) calculations could return negative values when certain object size categories have no data. The problem occurred because -1 sentinel values (used to indicate "no data") were being included in the mean calculation.
Notebook demonstrating the issue: https://colab.research.google.com/drive/1enb5xJ-28XLTw65GSr1ogCZl5OY7VFfF?usp=sharing
Note that this PR branches of #1895 to include the fix for always having the first ever object being a non-match. Merging that one first will slightly reduce the diff here.
When computing mAP for specific object sizes (small/medium/large), if a category had no ground truth objects, the precision array would contain -1 values. These sentinel values were incorrectly included when calculating the mean, …
=> fix: handle -1 sentinel values in mAP calculation to prevent negative results and mimic pycocotools behaviour

supervision/metrics/mean_average_precision.py, test/metrics/test_mean_average_precision.py
Objects were getting 0.0 mAP despite perfect IoU matches due to a bug in annotation ID assignment. The COCO evaluator treats ID=0 as "no match", but supervision was assigning the first annotation ID=0, causing it to be incorrectly classified as a false positive.
```python
"id": len(annotations),  # First object gets ID=0 → treated as "no match"
```
```python  
"id": len(annotations) + 1,  # Start IDs from 1 (0 means no match)
```
- **Before**: Single objects → 0.000 mAP, Multi-objects → partial failure
- **After**: All perfect predictions → 1.000 mAP
Added 3 regression tests covering single objects, multiple objects, and batch updates to prevent future regressions.
supervision 0.26.0 showing the bug:
https://colab.research.google.com/drive/1naVTb7qo7rbgT_AYaD8V9CvRdhK_wwPH?usp=sharing …
=> fix: ID=0 bug in Mean Average Precision calculation

supervision/annotators/utils.py, test/annotators/test_utils.py
The example trackers code is currently throwing an `AttributeError: 'numpy.int64' object has no attribute 'splitlines'`. This PR resolves the issue.
```python
CONFIDENCE_THRESHOLD = 0.3
NMS_THRESHOLD = 0.3
SOURCE_VIDEO_PATH = "/content/bikes-1280x720-1.mp4"
TARGET_VIDEO_PATH = "/content/bikes-1280x720-1-result.mp4"
frame_samples = []
def callback(frame, i):
result = model.infer(frame, confidence=CONFIDENCE_THRESHOLD)[0]
detections = sv.Detections.from_inference(result).with_nms(threshold=NMS_THRESHOLD)
detections = tracker.update(detections)
print(detections.tracker_id)
print(type(detections.tracker_id[0]))
print(type(str(detections.tracker_id[0])))
annotated_image = frame.copy()
annotated_image = box_annotator.annotate(annotated_image, detections)
annotated_image = …
```
=> fix: AttributeError: 'numpy.int64' object has no attribute 'splitlines'
