roboflow/supervision

mkdocs.yml
This PR adds Google Analytics to the Supervision documentation.
This change was tested by ensuring that the requisite GA tag loaded successfully on the project documentation.
N/A
N/A
=> Add Google Analytics to documentation

supervision/detection/core.py, test/detection/test_utils.py
Solve https://github.com/roboflow/supervision/issues/42
=> 🧪 ready for tests

docs/changelog.md, supervision/__init__.py, supervision/detection/core.py
Small housekeeping before `0.5.2` release. Only non-breaking changes.
=> 🧹 Small housekeeping before release

supervision/detection/line_counter.py
annotation function should return frame but it was not. So added return value
=> minor bug fixed

supervision/detection/core.py, supervision/file.py, supervision/internal.py, supervision/notebook/utils.py
- `Detections` documentation improvements
- `list_files_with_extensions` documentation improvements
- internal `deprecated` function added
- `plot_image` and `plot_images_grid` documentation improvements
=> major documentation improvements

supervision/detection/core.py
Like in the title, we are adding the ability to convert `YOLO-NAS` result into `sv.Detections`.
```python
>>> import cv2
>>> from super_gradients.training import models
>>> import supervision as sv
>>> image = cv2.imread(SOURCE_IMAGE_PATH)
>>> model = models.get('yolo_nas_l', pretrained_weights="coco")
>>> result = list(model.predict(image, conf=0.35))[0]
>>> detections = sv.Detections.from_yolo_nas(result)
```
=> 💜 Initial YOLO-NAS support

supervision/dataset/formats/yolo.py, supervision/utils/file.py
Fixed for #156 
Fixed and refactored `data.yaml` write and read methods
=> Yolo class name fix

supervision/dataset/core.py, supervision/dataset/formats/coco.py, supervision/utils/video.py
=> video generator with start and end position feature

supervision/dataset/utils.py, test/dataset/test_utils.py
=> Fixing empty detection coco dataset

.github/workflows/docs.yml
Update github action versions (actions/checkout@v3, actions/setup-python@v4) to recent versions.
=> chore: ✨ update github action versions (actions/checkout@v3, actions/setup-python@v4)

README.md, docs/index.md
This PR update readme.md installation sections for source and normal installation methods and also introduce poetry dev installation method as well. 
=> docs:  📝 update installation and source installation methods

supervision/metrics/detection.py, test/metrics/test_detection.py
Fix for https://github.com/roboflow/supervision/issues/215
- New unit tests
- Manual tests in google Colab: https://colab.research.google.com/drive/1WMFkOnapd4DOXGeb7B4xcGl3SDvWCTQQ?usp=sharing
Nope.
=> 🛠️ fix `detections_to_tensor`

docs/index.md, pyproject.toml
Title speak itself :) 
Python version requirements changed
=> docs: 📝 Update python version for supervision version 0.12.0

.github/workflows/docs.yml, .github/workflows/test.yml, poetry.lock, pyproject.toml
Since we move into pyproject toml, I am also adding other dev tools we used in project into toml file (linter,type checker and etc)
=> feat: 🛠  adding python dev tools into toml file

docs/changelog.md
This PR adds the changelog for v0.12.0 to the project documentation.
=> Add 0.12.0 changelog

pyproject.toml
Toml file License corrected and license section also added into toml file as well. An oversight I miss in toml file
=> docs: 📝 MIT license classifier added

CONTRIBUTING.md
It is a good idea to attach google colab link to easily reproduce the bug or expected results. Then minimal code will be shared among to all maintainers and contributor which will make process faster.
=> Contributing guidelines added for colab request

supervision/detection/core.py
This PR is in support for #187 
Find colab [here](https://drive.google.com/file/d/1R8mLUFsoflwTK4PSfnOXmKtw7Keu2zlX/edit?pli=1)
=> Paddledet support

supervision/tracker/byte_tracker/basetrack.py, supervision/tracker/byte_tracker/byte_tracker.py, supervision/tracker/byte_tracker/kalman_filter.py, supervision/tracker/byte_tracker/matching.py
This pr is intermediate version of #256 
- object class id is not a integrated in #256  but additional step was done from tracker result.
- additional step is removed
- typing added and fixed
- vectorized `box_iou` is integrated.
=> tracker optimized

supervision/detection/core.py, supervision/metrics/detection.py
`MeanAveragePrecision` code reformat and docs updates.
=> 🧹 small cleanup

supervision/detection/core.py
This pr enables directly convert tracker from ultralytics to `sv.Detections`
=> ultralytics tracker support added

docs/changelog.md
This PR updates `docs/changelog.md` with the release notes for the upcoming v0.13.0, to be released tomorrow.
=> v0.13.0 changelog

supervision/__init__.py, supervision/annotators/core.py
This PR supports all the requirements for #49 #170 
=> tracer in consistent format

docs/changelog.md, supervision/detection/core.py, supervision/tracker/byte_tracker/core.py
Simple typo fix in PaddleDetection in args in core.py and misc. pre-commit fixes 
-   [X] A documentation update in docstring
=> docs: 📝 typo fix for PaddleDetection in args

supervision/tracker/byte_tracker/core.py
In this version, I have modified the code by combining three loops into a single loop within the same method. This enhancement has resulted in improved efficiency.
YOUR_ANSWER
=> refactor: multi_predict()

.pre-commit-config.yaml
=> ci: :green_heart: pre-commit autoupdate

CONTRIBUTING.md
I notice that we have 2 code quality and I remove old one and improve current we use and some extras as well. 
cc @capjamesg @SkalskiP @hardikdava  
=> docs: 📝 code quality duplication removal and improvement in current

.github/workflows/test.yml
🔥 removal formatters from test ci saves time
=> ci(test): 🔥 removal formatters from test ci

supervision/utils/video.py
Added codecs and pos/keyword argument. Referring to this issue #380 
YOUR_ANSWER
-   [ ] Docs updated? What were the changes: Not yet
=> Adding Fourcc codecs option to VideoSink

supervision/detection/tools/inference_slicer.py
I am glad that my work inspired you on the inference slicer method!
I have only added the SAHI ICIP2022 URL into the inference slicer docstring. I hope you accept this PR :)
Keep up the great work 💯 
Bests
Fatih Akyon
=> add sahi paper url into docstring

CODE_OF_CONDUCT.md
Code of conduct based on : https://www.contributor-covenant.org/ 
Original URL : https://www.contributor-covenant.org/version/2/1/code_of_conduct/code_of_conduct.md
-   [X] Docs updated? What were the changes: CoC added
=> docs: 📝 code of conduct added

README.md
This PR adds a Discord invitation button to the README.
=> Add Discord button to README

supervision/__init__.py
Adding actual ColorMap enum into init.py 
=> fix(import): 🐞 add ColorMap into init.py

README.md
Adding HuggingFace Annotators Space link to `README.md`.
=> Adding HuggingFace Annotators Space link to `README.md`

examples/README.md, pyproject.toml
This PR is about adding more examples and introduction for how to add examples.
=> Adding example and  example guidelines

examples/README.md, supervision/tracker/byte_tracker/core.py
Reverts roboflow/supervision#436
=> Revert "#418 Make sv.ByteTrack work with segmentation model "

supervision/annotators/core.py
Annotator for drawing heatmap on an image using provided detections.
Heat is accumulated over time. Drawn as a semi-transparent overlay as blured circles.
https://github.com/roboflow/supervision/assets/6329901/4a7aa682-59ea-4c34-b569-8e6b40cea5d3
=> New feature HeatmapAnnotator

docs/draw/utils.md, supervision/__init__.py, supervision/draw/color.py, supervision/draw/utils.py
Expanded the drawing functionality by adding new utility methods 'draw_image', 'draw_line' and 'draw_rectangle' and imported them in supervision/__init__.py. Updated the documentation of draw/utils, to include 'draw_image'. Improved type hinting in draw/color.py and draw/utils.py. Also, some redundant comments and unnecessary immediate memory freeing line are removed from draw/utils.py to enhance code readability.
=> Add new drawing methods and improve type hints

demo.ipynb
This fix #509 problem on demo notebook and use new color lookup
=> fix(notebook): 🐛📘 sam detection ColorLookup param and enum added and sv version updated

docs/how_to/track_objects.md, supervision/annotators/core.py
YOUR_ANSWER
- Creation of How To: Track Objects Page
=> Builds: Create "How to: track objects" docs page #442

README.md
Thank you all who participate to hacktoberfest to make supervision awesome ! 🎉 🎉 🎉 🎉
=> docs: 🚀 hacktoberfest 2023 finished.

.pre-commit-config.yaml, pyproject.toml, test/utils/test_file.py
=> Updated tests to reflect changes in file content handling

.github/workflows/docs.yml
@SkalskiP  gh-pages failed action for deployment  fixed.
=> fix: 🐞 gh-pages permission fix for deployment

supervision/annotators/core.py
=> fixing typo TRACE -> TRACK

supervision/draw/color.py, test/draw/test_color.py
=> Add 'as_hex' method and corresponding test to `Color` class.

docs/draw/utils.md, supervision/__init__.py, supervision/draw/utils.py
dynamic font scale and line thickness calculation based on image resolution
=> dynamic font scale and line thickness calculation based on image resolution

pyproject.toml
This fix collab version conflicts for numpy,matplotlib,pillow
=> fix(format): 🐞 removal of numpy,matplotlib,pillow max versions for flexible to collab updates

.github/requirements-dev-min.txt, pyproject.toml
This change for re-configure numpy version for project and collab
=> fix(versions): 🐞 min numpy version changed to 1.21.2

demo.ipynb, examples/tracking/README.md, examples/tracking/script.py, examples/traffic_analysis/requirements.txt
=> fix(examples): 🐞 tracking LabelAnnotator and traffic_analysis deps fixed

pyproject.toml, supervision/detection/core.py
This PR adds a `sv.Detections.from_tensorflow_hub` data loader.
This change was tested using the following notebooks:
https://colab.research.google.com/drive/15upll1pKohWVpJ608wi6hSweOOGOcgQG
Note that the code does not load directly from this branch. I ran into caching issues when pulling updates. Instead, you'll see the same code in this branch to manipulate the bounding boxes into the correct format and turn them into an `sv.Detections` object. This happens in the "Visualizing the results" section.
N/A
I will add docs to this PR in a later commit.
=> Add `sv.Detections.from_tensorflow_hub` data loader.

supervision/detection/line_counter.py
Fix https://github.com/roboflow/supervision/issues/736.
=> `fix/line-zone-trigger-returns-value-error`

examples/speed_estimation/requirements.txt, examples/speed_estimation/ultralytics_example.py
Fix https://github.com/roboflow/supervision/issues/722.
=> `fix/speed-estimation-issue-when-detections-empty`

poetry.lock, pyproject.toml
Bump opencv version to latest and remove upper limit
=> fix: ✨ bump opencv version and remove upper limit

docs/annotators.md, supervision/annotators/core.py, supervision/assets/downloader.py, supervision/classification/core.py, supervision/dataset/core.py, supervision/detection/annotate.py, supervision/detection/core.py, supervision/detection/tools/inference_slicer.py, supervision/detection/utils.py, supervision/draw/color.py, supervision/draw/utils.py, supervision/geometry/utils.py, supervision/metrics/detection.py, supervision/tracker/byte_tracker/core.py, supervision/utils/file.py, supervision/utils/image.py, supervision/utils/notebook.py, supervision/utils/video.py
Removed '>>>' and '...' from examples and docs and improved some indentation. Please guide whether any changes are required in the documentation or in the PR. (Fix #758 ) 
=> Removed '>>>' and '...' from examples and docs and improved some indentation.

docs/changelog.md, pyproject.toml, supervision/annotators/core.py
- version bump from `0.18.0rc4` to `0.18.0`
- `supervision-0.18.0` release changelog update
- minor docs changes
=> `supervision-0.18.0` change log update

supervision/tracker/byte_tracker/core.py
Simple doc fix for tracker section 
=> docs: 📝 missing import of numpy and correct variable name in tracker section

supervision/utils/image.py
Simple doc fix for tracker section
=> small `crop_image` documentation fix

.github/workflows/docs.yml, poetry.lock, pyproject.toml
This change for install mike for multi doc version system and disable old CI temporarily it will be enable once old versions are pushed.
=> feat: ✨ mkdocs multi versioning package and old doc deployment CI disabled

.github/workflows/docs.yml, mkdocs.yml
This PR introduces a new continuous integration configuration for building our project documentation using mike. The change is implemented in the docs.yml GitHub Actions workflow file. The motivation for this change is to automate the process of generating and deploying our documentation for the develop branch. This will ensure that our documentation is always up-to-date with the latest changes in the codebase.
No specific deployment considerations are required for this change. The GitHub Actions workflow runs in the GitHub-hosted ubuntu-latest environment and does not incur any additional costs.
-   [X] Docs updated? The …
=> ci: 👷 documentation build via mike for develop tag configuration

examples/speed_estimation/inference_example.py, examples/speed_estimation/yolo_nas_example.py
Fix Inference and YOLO-NAS speed estimation examples.
=> fix inference and yolo nas speed estimation examples

README.md, docs/annotators.md, docs/changelog.md, docs/code_of_conduct.md, docs/contributing.md, docs/deprecated.md, docs/how_to/detect_and_annotate.md, docs/how_to/track_objects.md, docs/index.md, docs/license.md, docs/metrics/detection.md, examples/README.md, mkdocs.yml, supervision/annotators/core.py, supervision/classification/core.py, supervision/detection/line_counter.py, supervision/detection/tools/smoother.py
docs: ✨ docs urls in detection latest tag added
docs: ✨ contributing.md/code_of_conduct/license added into docs
docs: 📝 pypi and docker url added to footer
=> docs: ✨ fix url and coc and contributing.md, pythonic features of docs enabled, relative urls added.

docs/javascripts/cookbooks-card.js, docs/stylesheets/cookbooks-card.css, docs/theme/cookbooks.html
cookbooks page HTML optimisation + CSS update
=> cookbooks page HTML optimisation + CSS update

docs/javascripts/cookbooks-card.js, docs/stylesheets/cookbooks-card.css, docs/theme/cookbooks.html
- Removed cookbook card description
- Added names of users who contributed to the cookbook
- Added hover effect animating avatar when the name is hovered
- Improved behaviour of card flexbox
- Same label have same color across all cards
=> [Cookbooks] - Improved functionality of cookbook cards

docs/notebooks/annotate-video-with-detections.ipynb, docs/notebooks/download-supervision-assets.ipynb, docs/notebooks/object-tracking.ipynb, docs/theme/cookbooks.html
count objects crossing the line
=> [Cookbooks] - Count Objects Crossing the Line

docs/theme/cookbooks.html
Count People Crossing the Line Cookbook
=> [Cookbooks] - Count People Crossing the Line 2

docs/theme/cookbooks.html
`Count People Crossing the Line` cookbook updates.
=> `Count People Crossing the Line` cookbook updates.

CONTRIBUTING.md
Updating `CONTRIBUTING.md` with Cookbooks contributors guidelines.
=> `CONTRIBUTING.md` updates.

docs/index.md, docs/theme/index.html
docs: 📝 h1 title Home removed from index.md
=> docs: 📝 h1 title Home removed from index.md

docs/cookbooks.md, docs/javascripts/cookbooks-card.js
=> fix: 🐞 cookbook z-index fix for author avatar

supervision/detection/tools/polygon_zone.py, supervision/utils/internal.py
update `deprecated_parameter` docs
=> update `deprecated_parameter` docs

supervision/utils/internal.py
I added warning filter for turn off deprecation via env variable and set warning filter to make sure it shows cleaner warning message
=> fix: 🐞 Custom warning type 'SupervisionWarning' added

supervision/annotators/utils.py, supervision/utils/notebook.py
feat(ImageType): 🚀 sv.plot_images_grid and sv.plot_image can accept ImageType
=> feat(ImageType): 🚀 sv.plot_images_grid and sv.plot_image can accept ImageType

.github/workflows/test-doc.yml
This test action will show is docs build before push and make sure we can avoid notebooks bugs
=> feat: 📚 add docs test workflow

examples/traffic_analysis/inference_example.py, examples/traffic_analysis/requirements.txt, examples/traffic_analysis/ultralytics_example.py, test/detection/test_polygonzone.py
fix: 🐞 update PolygonZone test and update traffic-analysis depricated codes are updated
=> fix: 🐞 update PolygonZone test and update traffic-analysis depricated codes are updated

docs/annotators.md, docs/changelog.md, supervision/annotators/core.py
Update `changelog.md` with `supervision-0.19.0` features
=> `supervision-0.19.0` release changelog

docs/draw/utils.md, examples/count_people_in_zone/requirements.txt, examples/heatmap_and_track/requirements.txt, examples/speed_estimation/requirements.txt, examples/tracking/requirements.txt, examples/traffic_analysis/requirements.txt, supervision/__init__.py, supervision/annotators/core.py, supervision/draw/utils.py
Testing adding a color border to crop annotator.
=> adding color border to crop annotator poc

docs/how_to/detect_and_annotate.md, docs/how_to/detect_small_objects.md, docs/index.md, mkdocs.yml
https://github.com/roboflow/supervision/assets/26109316/33f25e9c-eb2c-4a1f-aae0-9a414801ccd1
=> Detect Small Objects documentation

docs/how_to/detect_small_objects.md
https://github.com/roboflow/supervision/assets/26109316/cded6752-ef1f-4bb0-b096-e525227ff5b1
=> Detect Small Objects documentation 2

test/detection/test_utils.py
`get_data_item` unit tests covering https://github.com/roboflow/supervision/pull/1062 changes.
=> `get_data_item` unit tests

.github/workflows/publish-test.yml, .github/workflows/publish.yml
Reverts roboflow/supervision#1064
=> Revert "fix: 🐞 ci trigger error fix"

docs/how_to/detect_and_annotate.md, supervision/detection/core.py
- How to Detect and Annotate guide extended with Transformers segmentation example
- `from_transformers` docs extended with Transformers detection example
- Fix for `RuntimeError: Boolean value of Tensor with no values is ambiguous`
=> `from_transformers` improvements

README.md, docs/index.md
=> docs: 📚 conda and mamba installation methods added

docs/utils/notebook.md
YOUR_ANSWER
-   [ x] Docs updated? What were the changes:
fixed formatting error
=> fix: formatting in notebook.md

docs/how_to/detect_and_annotate.md, docs/how_to/save_detections.md, docs/utils/image.md, mkdocs.yml, supervision/__init__.py, supervision/annotators/core.py, supervision/draw/color.py, supervision/utils/conversion.py, supervision/utils/image.py, supervision/utils/iterables.py, test/utils/test_image.py
- fixed `crop_image` types and docstrings
- renamed `resize_image` to `scale_image` + fix types and docstrings
- renamed `resize_image_keeping_aspect_ratio` to `resize_image` + fix types and docstrings
=> docs improvements related to #1028 PR 

examples/count_people_in_zone/inference_example.py, examples/count_people_in_zone/ultralytics_example.py, examples/speed_estimation/inference_example.py, examples/speed_estimation/ultralytics_example.py, examples/speed_estimation/yolo_nas_example.py, pyproject.toml
some of our examples stopped working after `supervision-0.20.0` release; this PR aims to solve those issues
=> fix/code examples after supervision 0.20.0 release

examples/speed_estimation/requirements.txt, examples/time_in_zone/requirements.txt, examples/traffic_analysis/requirements.txt
Pin inference version in all examples and solve https://github.com/roboflow/supervision/issues/1152 bug
=> pin inference version in examples

examples/count_people_in_zone/requirements.txt, examples/speed_estimation/requirements.txt, examples/time_in_zone/requirements.txt, examples/tracking/requirements.txt, examples/traffic_analysis/requirements.txt
pin inference version to `0.9.17` in supervision examples
=> pin inference version to 0.9.17

supervision/detection/core.py
See #765 
-   Bug fix (non-breaking change which fixes an issue)
-   New feature (non-breaking change which adds functionality)
Try putting in a configuration without a mask and a config with a mask to see if the value fits well
Nothing
There is nothing special
=> Mmdetection mask

mkdocs.yml
=> minor docs change: rename How To - Track Objects

mkdocs.yml
Shortened the name of object tracking how-to title.
=> Docs: shorter title for object tracking how-to

docs/changelog.md, mkdocs.yml, pyproject.toml, supervision/detection/core.py, supervision/detection/lmm.py, supervision/detection/utils.py, test/detection/test_lmm.py
final changes before `supervision-0.21.0`
=> final changes before `supervision-0.21.0`

CONTRIBUTING.md
**Fixed a grammatical mistake in CONTRIBUTING.md to increase the quality of the document.**
**No dependencies are required.**
**No testing is required. Only some text was changed.**
**None**
**No Changes**
=> Fix Grammatical Mistake In CONTRIBUTING.md

supervision/__init__.py, supervision/utils/file.py
- This PR will expose some file read/write utilities function for easy to use.
- File input can now support Path or string
YOUR_ANSWER
-   [x] Docs updated? What were the changes: docstrings updated
=> file utilities ret-type updated and extended function to work with Pathlib

README.md
Requested by @trevorhlynnRF: changing hackfest banner to point to projects page
=> Readme: change hackfest banner link to project page

CONTRIBUTING.md, pyproject.toml
This PR updates the `CONTRIBUTING.md` file to improve its structure. Key changes include:
- Added a table of contents for easier navigation
- Added Code of Conduct reference 
- Expanded installation instructions for contributors
- Updated guidelines for branching and committing messages
- Enhanced sections on code style, documentation, and testing
=> docs: revise and restructure CONTRIBUTING.md

docs/detection/utils.md, supervision/__init__.py, supervision/detection/core.py, supervision/detection/utils.py, test/detection/test_utils.py
Updated `xywh_to_xyxy` and added `xcycwh_to_xyxy` box utils.
=> `xywh_to_xyxy` and `xcycwh_to_xyxy` box utils

supervision/annotators/core.py
Fix for https://github.com/roboflow/supervision/issues/1368.
=> fix incorrect annotators docstring

supervision/annotators/core.py
Fix for Issue #1371 
I'll update the PR with a [colab](https://colab.research.google.com/drive/1mZb1aYRM-ncKZwsCyKDzQuqABPuH--Mt?usp=sharing) notebook
=> Changed as_rgb() to as_bgr() in LabelAnnotator

.github/workflows/test-doc.yml, CONTRIBUTING.md, docs/javascripts/cookbooks-card.js, docs/stylesheets/cookbooks-card.css, docs/theme/cookbooks.html, poetry.lock, pyproject.toml
- Fix cookbook cards that make them clickable
- Combine multiple pip install commands into a single step
- Simplify the workflow by reducing redundancy
- Ensure all necessary dependencies are installed in one go
=> docs: cookbook visual fix for cards and small ci doc dev changes

docs/notebooks/annotate-video-with-detections.ipynb, docs/notebooks/object-tracking.ipynb, test/dataset/test_utils.py, test/detection/test_utils.py
Hello, I saw some typos and I fixed them.
* Corrected typos in the codebase for improved readability.
=> fix: documentation and notebook spell fixes

test/dataset/test_core.py, test/detection/test_polygonzone.py
Hello, 
I saw some warnings when I run the tests. So, I resolved these warnings.
*  Fix warnings found during test execution to ensure a clean test suite.
=> fix(refactor): 🐞 Update deprecated usages of supervision tests to the latest version

supervision/detection/core.py
Initial ncnn support added
-   [x] Docs updated? What were the changes: from_ncnn docs added
Collab link : https://colab.research.google.com/drive/1wbciO5reYvl2372LeANnvgFbSK_mNi1l?usp=sharing
=> feat: ✨ initial ncnn object detection support added

docs/changelog.md, docs/deprecated.md, docs/detection/tools/line_zone.md, docs/detection/tools/polygon_zone.md, docs/detection/utils.md, docs/keypoint/annotators.md, docs/utils/image.md, docs/utils/video.md, supervision/detection/line_zone.py, supervision/detection/tools/polygon_zone.py
Changelog, deprecations and small fixes ahead of the 0.24.0 release.
Docs were tested by replacing `/0.24.0/` with `develop`.
Tests were run and doc regressions carefully checked for. 
=> Feat/changelog 0.24.0

pyproject.toml
https://safjan.com/the-importance-of-adding-py-typed-file-to-your-typed-package/
N/A
N/A
=> feat: adding type hinter markers in package

supervision/detection/tools/polygon_zone.py
Added example usage in PolygonZone docs.
* Added PolygonZone example
=> Add usage example in Polygon Zone docs

README.md
Hacktoberfest ended so it is time to remove the banner.
=> docs: 📝 hacktoberfest banner removed

.github/workflows/publish-docs.yml, .github/workflows/test-doc.yml
Switch the checkout back to using fetch-depth 0 as suggested by the docs build process.
=> Update docs checkout to use fetch-depth: 0

supervision/detection/core.py
Just some small typos in the docs..
-   [ x] Docs updated? What were the changes: Fix example in docstring
=> Fix typos in Detections merge doc string

docs/detection/utils.md, supervision/__init__.py, supervision/detection/utils.py, test/detection/test_utils.py
xyxy_to_xcycarh utility conversion function added
=> feat: ✨ add xyxy_to_xcycarh conversion function

supervision/annotators/core.py
Add support for non-str labels in `LabelAnnotator`.
=> feat(LabelAnnotator): add support for non-str labels

pyproject.toml, supervision/annotators/utils.py, supervision/draw/color.py
This pull request introduces a minor version bump to the project and adds support for a new color (`GREY`) to handle pending track annotations in the `ColorLookup` logic.
=> make `supervision` annotators compatible with `trackers` pending tracker ID

supervision/utils/video.py
Fix the following error in `sv.process_video`:
```
UnboundLocalError: cannot access local variable 'total_frames' where it is not associated with a value
```
=> fix: `UnboundLocalError` in `process_video`

docs/how_to/track_objects.md, supervision/utils/image.py
Fixes https://github.com/roboflow/supervision/issues/1827
By running `mkdocs serve` 
=> fix(docs): Track Objects on Video example not retrieving class name correctly

docs/detection/utils.md
This PR fixes the style of the /detection/utils/ page.
Style change.
Run `mkdocs serve` then open http://127.0.0.1:8000/detection/utils/.
N/A
N/A
=> Fix broken page

supervision/detection/core.py, supervision/detection/vlm.py, test/detection/test_vlm.py
=> chore: address feedback for google gemini support

supervision/detection/core.py
docs: 📝 enhance prompt engineering tips for Qwen2.5-VL and Moondream models
=> docs: 📝 enhance prompt engineering tips for Qwen2.5-VL and Moondream models

pyproject.toml, supervision/detection/core.py, supervision/detection/tools/inference_slicer.py, supervision/detection/utils/iou_and_nms.py
=> fix:  🐞 update inference_slicer.py for improved detection handling

.github/CODEOWNERS, docs/changelog.md, pyproject.toml
This PR updates the changelog for release 0.26.1 with the fixes.
=> update: changelog for 0.26.1

docs/detection/utils/vlms.md, mkdocs.yml, supervision/__init__.py, supervision/detection/utils/vlms.py, supervision/metrics/mean_average_precision.py, test/detection/utils/test_vlms.py
Utils allowing to match faulty class name generated by VLMs with exact class names.
=> `edit_distance` and `fuzzy_match_index` that will allow to match faulty class name generated by VLMs with exact class names

examples/time_in_zone/requirements.txt, examples/time_in_zone/scripts/download_from_youtube.py, supervision/annotators/utils.py, test/annotators/test_utils.py
- Fix `PENDING_TRACK_ID` guard to work even when `color_lookup` is `np.array`
- Fix `pytube` 404
=> fix for #1911

supervision/keypoint/core.py
This is a small PR that fixed the usage of capital letter DEVICE when 'device' was intended to use.
-   [ ] Docs fix (non-breaking change which fixes an issue)
No tests required, superificial change to the docs.
=> Corrected vitpose docstring

docs/utils/image.md, supervision/utils/image.py
Missing commits with updated visuals.
=> docs/refactor 0.27.0 missing commits
